### ISSUE TITLE
Wrong deduplication for `service` and `connect` dependencies

### ISSUE THREAD

**Issue by danieleva** [hashicorp/consul-template#1458] opened 2021-03-09 15:48 UTC
`dependency.HealthService.String()` returns the same value for `service` and `connect` invocation, and that breaks templates when both functions are called with the same parameter.
In my case I have an external service registered in the catalog, and a terminating-gateway configured for it. I want to get IP:Port from `connect`,  and some metadata from `service`, and that doesn't work
### Consul Template version

consul-template v0.25.1

### Configuration

```hcl
consul-template -dry -once -template ./sample.tpl
```

This template is not very useful but it's perfect to pinpoint the bug
```liquid
{{ range service "myservice" }} {{ .Name}} {{end}}
{{ range connect "myservice" }} {{ .Name}} {{end}}
{{ printf "%#v" (service "myservice") }}
{{ printf "%#v" (connect "myservice") }}
```

"myservice" is registered directly into consul catalog, and a terminating-gateway is assigned to it via config entry

### Command

```shell
consul-template -dry -once -template ./sample.tpl
```

### Expected behavior

I would expect the output to be:
```liquid
[]*dependency.HealthService{(*dependency.HealthService)(0xc000001234)}
[]*dependency.HealthService{(*dependency.HealthService)(0xc000005678)}
 myservice
 terminating-gateway
```

### Actual behavior

What actually happened?

```liquid
[]*dependency.HealthService{(*dependency.HealthService)(0xc000001234)}
[]*dependency.HealthService{(*dependency.HealthService)(0xc000001234)}
 myservice
 myservice
```

### Steps to reproduce

Any template that uses both functions will trigger it.

**Comment by eikenb** [comment] 2021-03-09 19:03
Thanks for the report @danieleva and much thanks for the simple case to reproduce, that always makes things way easier on my end which I appreciate.

Looks like like both connect and service look-ups are using  the same keys for the cache/value-store. It should be a straightforward fix and will be in the next release, which should be soon as the latest release had an annoying regression in the shell handling.

**Closed** 2021-05-27 20:49 UTC
Labels: bug
