### ISSUE TITLE
consul-template --version outputs content to stderr

### ISSUE THREAD

**Issue by arturhoo** [hashicorp/consul-template#518] opened 2016-01-20 14:50 UTC
I can't tell if it is the expected behaviour, but it is inconsistent with the `consul` binary.

**Comment by sethvargo** [comment] 2016-01-20 15:25
Dupe of https://github.com/hashicorp/consul-template/issues/234. Please see the conversation there to understand why we use stderr :smile:

**Closed by sethvargo** 2016-01-20 15:25 UTC

**Comment by arturhoo** [comment] 2016-01-20 15:27
Somehow missed that, thanks!
