### ISSUE TITLE
service in a range loop got empty

### ISSUE THREAD

**Issue by kdlan** [hashicorp/consul-template#142] opened 2015-01-09 03:30 UTC
I have keys like 

```
/supported-service/consul
```

and services like
```
consul
```

and a template

```
{{range $data := ls "supported-service"}}
   {{service $data.Key}}
{{end}}
```

exectue the consul-template
```
> CONSUL_TEMPLATE_LOG=debug consul-template -template "test.template" -dry -once
2015/01/09 11:25:39 [DEBUG] (cli) creating Runner
2015/01/09 11:25:39 [DEBUG] (runner) RunAll
2015/01/09 11:25:39 [DEBUG] (runner) checking template: &main.Template{Path:"/root/consul-template/test.template", dependencies:[]main.dependencyContextBridge{(*main.storeKeyPrefixBridge)(0xc2080360b8)}}
2015/01/09 11:25:39 [DEBUG] (runner) cannot render template (not ready), continuing
2015/01/09 11:25:39 [DEBUG] (cli) creating Consul API client
2015/01/09 11:25:39 [DEBUG] (cli) creating Watcher
2015/01/09 11:25:39 [DEBUG] (cli) looping for data
2015/01/09 11:25:39 [DEBUG] (watcher) starting watch
2015/01/09 11:25:39 [DEBUG] (watcher) all pollers have started, waiting for finish
2015/01/09 11:25:39 [DEBUG] (storeKeyPrefix "supported-service") starting fetch
2015/01/09 11:25:39 [DEBUG] (storeKeyPrefix "supported-service") querying Consul with &{Datacenter: AllowStale:false RequireConsistent:false WaitIndex:0 WaitTime:1m0s Token:}
2015/01/09 11:25:39 [DEBUG] (storeKeyPrefix "supported-service") Consul returned 1 key pairs
2015/01/09 11:25:39 [INFO] (storeKeyPrefix "supported-service") received data from consul
2015/01/09 11:25:39 [INFO] (cli) received data from Watcher for storeKeyPrefix "supported-service"
2015/01/09 11:25:39 [DEBUG] (runner) Receiving dependency storeKeyPrefix "supported-service"
2015/01/09 11:25:39 [INFO] (cli) invoking Runner
2015/01/09 11:25:39 [DEBUG] (runner) RunAll
2015/01/09 11:25:39 [DEBUG] (runner) checking template: &main.Template{Path:"/root/consul-template/test.template", dependencies:[]main.dependencyContextBridge{(*main.storeKeyPrefixBridge)(0xc2080360b8)}}
2015/01/09 11:25:39 [DEBUG] (runner) checking ctemplate:
2015/01/09 11:25:39 [DEBUG] (watcher) closing finish channel
>

   []


2015/01/09 11:25:39 [DEBUG] (runner) rendered: true
2015/01/09 11:25:39 [DEBUG] (cli) looping for data
2015/01/09 11:25:39 [INFO] (cli) received finished signal, exiting now
```

but if I change the template to

```
{{range $data := ls "supported-service"}}
   {{service $data.Key}}
{{end}}

This is additional template
{{service "consul"}}
```

The `{{service "consul"}}` will return a non-empty array`

```
> CONSUL_TEMPLATE_LOG=debug consul-template -template "/root/consul-template/test.template" -dry -once
2015/01/09 11:27:19 [DEBUG] (cli) creating Runner
2015/01/09 11:27:19 [DEBUG] (runner) RunAll
2015/01/09 11:27:19 [DEBUG] (runner) checking template: &main.Template{Path:"/root/consul-template/test.template", dependencies:[]main.dependencyContextBridge{(*main.storeKeyPrefixBridge)(0xc2080360c0), (*main.serviceDependencyBridge)(0xc2080360e8)}}
2015/01/09 11:27:19 [DEBUG] (runner) cannot render template (not ready), continuing
2015/01/09 11:27:19 [DEBUG] (cli) creating Consul API client
2015/01/09 11:27:19 [DEBUG] (cli) creating Watcher
2015/01/09 11:27:19 [DEBUG] (cli) looping for data
2015/01/09 11:27:19 [DEBUG] (watcher) starting watch
2015/01/09 11:27:19 [DEBUG] (watcher) all pollers have started, waiting for finish
2015/01/09 11:27:19 [DEBUG] (storeKeyPrefix "supported-service") starting fetch
2015/01/09 11:27:19 [DEBUG] (storeKeyPrefix "supported-service") querying Consul with &{Datacenter: AllowStale:false RequireConsistent:false WaitIndex:0 WaitTime:1m0s Token:}
2015/01/09 11:27:19 [DEBUG] (service "consul [passing]") starting fetch
2015/01/09 11:27:19 [DEBUG] (service "consul [passing]") querying Consul with &{Datacenter: AllowStale:false RequireConsistent:false WaitIndex:0 WaitTime:1m0s Token:}
2015/01/09 11:27:19 [DEBUG] (storeKeyPrefix "supported-service") Consul returned 1 key pairs
2015/01/09 11:27:19 [INFO] (storeKeyPrefix "supported-service") received data from consul
2015/01/09 11:27:19 [INFO] (cli) received data from Watcher for storeKeyPrefix "supported-service"
2015/01/09 11:27:19 [DEBUG] (runner) Receiving dependency storeKeyPrefix "supported-service"
2015/01/09 11:27:19 [INFO] (cli) invoking Runner
2015/01/09 11:27:19 [DEBUG] (runner) RunAll
2015/01/09 11:27:19 [DEBUG] (runner) checking template: &main.Template{Path:"/root/consul-template/test.template", dependencies:[]main.dependencyContextBridge{(*main.storeKeyPrefixBridge)(0xc2080360c0), (*main.serviceDependencyBridge)(0xc2080360e8)}}
2015/01/09 11:27:19 [DEBUG] (runner) cannot render template (not ready), continuing
2015/01/09 11:27:19 [DEBUG] (cli) looping for data
2015/01/09 11:27:19 [DEBUG] (service "consul [passing]") Consul returned 3 services
2015/01/09 11:27:19 [DEBUG] (service "consul [passing]") 3 services after health check status filtering
2015/01/09 11:27:19 [INFO] (service "consul [passing]") received data from consul
2015/01/09 11:27:19 [INFO] (cli) received data from Watcher for service "consul [passing]"
2015/01/09 11:27:19 [DEBUG] (runner) Receiving dependency service "consul [passing]"
2015/01/09 11:27:19 [INFO] (cli) invoking Runner
2015/01/09 11:27:19 [DEBUG] (runner) RunAll
2015/01/09 11:27:19 [DEBUG] (runner) checking template: &main.Template{Path:"/root/consul-template/test.template", dependencies:[]main.dependencyContextBridge{(*main.storeKeyPrefixBridge)(0xc2080360c0), (*main.serviceDependencyBridge)(0xc2080360e8)}}
2015/01/09 11:27:19 [DEBUG] (runner) checking ctemplate:
2015/01/09 11:27:19 [DEBUG] (watcher) closing finish channel
>

   [0xc20806af00 0xc20806aea0 0xc20806ae40]


This is additional template
[0xc20806af00 0xc20806aea0 0xc20806ae40]
2015/01/09 11:27:19 [DEBUG] (runner) rendered: true
2015/01/09 11:27:19 [DEBUG] (cli) looping for data
2015/01/09 11:27:19 [INFO] (cli) received finished signal, exiting now
```

**Comment by sethvargo** [comment] 2015-01-09 18:32
Hi @kdlan,

Thank you for the bug report. This is actually a duplicate of #64. Please track that issue for progress.

**Closed by sethvargo** 2015-01-09 18:32 UTC
