### ISSUE TITLE
Add template watch from KV store

### ISSUE THREAD

**Issue by gbbirkisson** [hashicorp/consul-template#711] opened 2016-09-19 16:33 UTC
It would be great to be able to store my templates in the Key/Value store. So you would run consul-template something like this:

```bash
$ consul-template \
    -consul=<server> \
    -template='{{key "service/haproxy/template"}}:/etc/haproxy/haproxy.conf' \
    -exec='haproxy -f /etc/haproxy/haproxy.conf'
```

Then when the template changes in the KV store, consul-template would reload the config or restart child process.

**Comment by sethvargo** [comment] 2016-09-19 19:15
Hi there,

This is a duplicate of https://github.com/hashicorp/consul-template/issues/705, which is also a duplicate of an very early request. This is generally not a good idea, since you have no checks-and-balances. If CT fails to parse the template, it will exit immediately. That means, if someone makes a simple typo, the CT daemon dies across the entire cluster. It's generally not a good idea and I wouldn't advocate for it. If you _really_ want this behavior, you could run two Consul Template processes, one that ingresses the key from consul and writes to a file and then another that ingresses that file.

**Closed by sethvargo** 2016-09-19 19:15 UTC

**Comment by robottaway** [comment] 2016-09-28 17:16
I do not follow this line of reasoning. Bad config is bad config. We already have the issue of agents dying you describe... just it follows from Chef dropping the bad files rather than having them fetched out of Consul directly. The only difference I see if how fast you fail which with Chef could be a very long time if someone in my Org has locked it up and hosts are not converging for a long period.

As far as checks and balances I do not see any being prescribed by Consul-Template other than maybe the host level configuration that dictates which templates are being rendered. Still this is not a solution for keeping bad templates from killing the process is it?

**Comment by dechandler** [comment] 2020-03-20 19:20
It doesn't make any sense that a template in a file would be any more trustworthy than one that's in a Consul KV entry. It's all user input, which *fundamentally* should not be allowed to crash any serious application. That seems like a major issue that should be fixed.
