### ISSUE TITLE
Get unique tags

### ISSUE THREAD

**Issue by hoffoo** [hashicorp/consul-template#200] opened 2015-02-18 20:55 UTC
I would like to list all tags and create groups of hosts based on them. The issue is that I only want one group per tag, even if multiple services in the Catalog have the same tag. Right now when I range by service im getting duplicate tags (which makes perfect sense).

I tried various things i read trough but cannot come up with a workaround for me (If only I could use a map in a template or just add a function on the fly).

Any ideas would be super helpful!

**Comment by sethvargo** [comment] 2015-02-18 21:12
Hi @hoffoo 

This is a duplicate of https://github.com/hashicorp/consul-template/issues/33. Right now this is not possible because Consul does not provide a way to query on _just_ a tag. Your case is interesting because you need to invert the result from `services` (i.e. `map[tag]services` instead of map[service]tags`). Unfortunately this is not something that is currently possible due to the upstream bug in Consul. You can read more information on the linked issue. Sorry about that.

**Closed by sethvargo** 2015-02-18 21:12 UTC

**Comment by hoffoo** [comment] 2015-02-18 21:24
no problem thanks a lot for clarifying!

**Comment by sielaq** [comment] 2015-03-01 13:31
Hi @hoffoo,

We have workaround it like this, 
```
{{range services}}
  {{range $tag, $services := service .Name|byTag}}
    #{{$tag}}
    {{$service_name := (index $services 0).Name}}
    {{$service_name}}
    {{range $services}}
      {{.Node}} {{.Port}} {{.Address}}
    {{end}}
  {{end}}
{{end}}

```
or you can ensure only specific Tags like:
```
{{range services}}
  {{range $tag, $services := service .Name|byTag}}
    #{{$tag}}
    {{if or (eq $tag "YOUR_TAG_1") (eq $tag "YOUR_TAG_2")}}
      {{$service_name := (index $services 0).Name}}
      {{$service_name}}
      {{range $services}}
        {{.Node}} {{.Port}} {{.Address}}
      {{end}}
    {{end}}
  {{end}}
{{end}}
```
I'm not sure if this would also help for you.

**Comment by scalp42** [comment] 2015-09-01 20:48
@sielaq in your example the `if or` acts as a `AND` operation. How can we query `YOUR_TAG_1` *OR* `YOUR_TAG_2` ?

**Comment by sielaq** [comment] 2015-09-02 05:42
Actually it behaves like logical  `OR` ,  if any appearance of `YOUR_TAG_1` or `YOUR_TAG_2` exists in tags, then service is generated. Might be you are setting tags not properly (for ex. you have only one big tag).

see our HAproxy set up in PaaS project which works already
https://github.com/eBayClassifiedsGroup/PanteraS/blob/master/infrastructure/template.conf
