### ISSUE TITLE
Allow Consul K/V a default value if that key does not exist

### ISSUE THREAD

**Issue by narcisbcn** [hashicorp/consul-template#326] opened 2015-06-22 12:14 UTC
It would be useful to have the capability to set a default value for a key if that key has not been set. Right now you can do things like this:
```
{{if key "service/jboss/node1"}}
  loadfactor = {{key "service/jboss/node1"}}
{{else}}
   loadfactor=10
{{end}}
```

But I think the syntax of our templates would be cleaner if we are able to do something like this:
````
{{key "service/jboss/node1", 10}}
````

**Comment by sethvargo** [comment] 2015-06-22 13:08
Hi @narcisbcn 

This is a duplicate of https://github.com/hashicorp/consul-template/issues/323. I think the `if/else` syntax is very declarative and easy for a user to understand the logical flow in the template :smile:. Thanks!

**Closed by sethvargo** 2015-06-22 13:08 UTC

**Comment by selboo** [comment] 2016-11-22 09:55
{{key_or_default "service/redis/maxconns@east-aws" "5"}}
