### ISSUE TITLE
Consul Template - HaProxy and Define Domain

### ISSUE THREAD

**Issue by zekiunal** [hashicorp/consul-template#388] opened 2015-09-08 09:21 UTC
Hello 

I am trying to do configure HaProxy with Consul Template.
````
global
  log 127.0.0.1   local0
  maxconn 4096
  user haproxy
  group haproxy

defaults
  log     global
  mode    http
  option  httplog
  option  dontlognull
  stats enable
  stats uri /stats
  retries 3
  option redispatch
  timeout connect 5s
  timeout client 50s
  timeout server 50s
  balance roundrobin

frontend http
  bind 0.0.0.0:80
  # Define hosts
	{{range $i,$a:=services}}
		{{$path:=.Name}}
		{{range .Tags}}
			{{if eq . "backend"}}
				{{range $c,$d:=service $path}}
					{{if eq $c 0}}
						acl host{{$i}} hdr(host) -i {{$path}}.domain.com
					{{end}}
				{{end}}
			{{end}}
		{{end}}
	{{end}}
  ### figure out which one to use
	{{range $i,$a:=services}}
		{{$path:=.Name}}
		{{range .Tags}}
			{{if eq . "rest"}}
				{{range $c,$d:=service $path}}
					{{if eq $c 0}}
						use_backend {{$path}} if host{{$i}}
					{{end}}
				{{end}}
			{{end}}
		{{end}}
	{{end}}

{{range $i,$a:=services}}
	{{$path:=.Name}}
	{{range .Tags}}
		{{if eq . "backend"}}
			backend {{$path}} 0.0.0.0:80
				mode http
				balance roundrobin
				option  httplog
				option  httpclose
				option  forwardfor
				{{range service $path}}
					server {{.Node}} {{.Address}}:{{.Port}} weight 1
				{{end}}
		{{end}}
	{{end}}
{{end}}
````

Here is the result haproxy config file .

```
global
  log 127.0.0.1   local0
  maxconn 4096
  user haproxy
  group haproxy

defaults
  log     global
  mode    http
  option  httplog
  option  dontlognull
  stats enable
  stats uri /stats
  retries 3
  option redispatch
  timeout connect 5s
  timeout client 50s
  timeout server 50s
  balance roundrobin

frontend http
  bind 0.0.0.0:80
  # Define hosts
  acl host3 hdr(host) -i management.domain.com
  acl host5 hdr(host) -i www.domain.com
  ### figure out which one to use
  use_backend management if host3
  use_backend www if host5


backend api.oauth 0.0.0.0:80
    mode http
    balance roundrobin
    option  httplog
    option  httpclose
    option  forwardfor
	
backend management 0.0.0.0:80
    mode http
    balance roundrobin
    option  httplog
    option  httpclose
    option  forwardfor
    server 066067d2971b 172.17.0.61:9093 weight 1
	server 066067d2972c 172.17.0.62:9093 weight 1
	server 066067d2973d 172.17.0.63:9093 weight 1
backend www 0.0.0.0:80
    mode http
    balance roundrobin
    option  httplog
    option  httpclose
    option  forwardfor

    server e5c11dc4440d 172.17.0.3:9091 weight 1
    server e5c11dc4441e 172.17.0.4:9091 weight 1
    server e5c11dc4442f 172.17.0.5:9091 weight 1
````

If you look at "backend api.oauth 0.0.0.0:80" part.  api.oauth.domain.com's nodes not listing in the config file. 

And not listing in the frontend side. 

````
frontend http
  bind 0.0.0.0:80
  # Define hosts
  acl host3 hdr(host) -i management.domain.com
  acl host5 hdr(host) -i www.domain.com
  ??????????????????????????????????? where is api.oauth.domain.com
  ### figure out which one to use
  use_backend management if host3
  use_backend www if host5
??????????????????????????????????? where is use_backend api.oauth if hostX
````

Becouse , "api.oauth" key not working in the range loop. It has got "." character and i could not escaped it.

$path = "api.oauth" (service .Name)

{{range service $path}}

How can i escape "." in the range loops? 

How can i handle this problem? 

I am sending configuration like this. 

### For api.oauth.domain.com
````
docker exec -d ${CID} /bin/bash -c 'echo "{\"service\": {\"name\": \"api.oauth\", \"tags\": [\"prod\",\"rest\",\"backend\"], \"port\": '${PORT}'}}" >> /etc/consul.d/app.json'
````
### For management.domain.com
````
docker exec -d ${CID} /bin/bash -c 'echo "{\"service\": {\"name\": \"management\", \"tags\": [\"prod\",\"backend\"], \"port\": '${PORT}'}}" >> /etc/consul.d/app.json'
````
### For www.domain.com
````
docker exec -d ${CID} /bin/bash -c 'echo "{\"service\": {\"name\": \"www\", \"tags\": [\"prod\",\"backend\"], \"port\": '${PORT}'}}" >> /etc/consul.d/app.json'
````

How can i send domain names with alternative way?

I am sorry for low level english.

**Comment by sethvargo** [comment] 2015-09-08 18:03
Hi @zekiunal 

This looks like a duplicate of #356 and #354:

> This is a known issue, but not a bug. You should not use dots in service names and Consul specifically calls this out in the documentation; it messes with the DNS query interface.
> 
> The "dots" have special meaning in CT as it specifies the tag search attribute.

**Closed by sethvargo** 2015-09-08 18:03 UTC
