### ISSUE TITLE
if service name include dot,will throw [invalid health service dependency format]

### ISSUE THREAD

**Issue by qintang** [hashicorp/consul-template#643] opened 2016-05-23 09:34 UTC
if service name include dot,like {{service "server1/1.0"}}
will throw [invalid health service dependency format]

**Comment by sethvargo** [comment] 2016-05-23 14:52
Duplicate of https://github.com/hashicorp/consul-template/issues/295. While Consul allows it, it will not work with Consul's DNS querying interface and is generally not recommended. We do not support dots in service names in Consul Template.

**Closed by sethvargo** 2016-05-23 14:52 UTC
