### ISSUE TITLE
Consul-template cannot unwrap tokens generated by Vault agent

### ISSUE THREAD

**Issue by greenbrian** [hashicorp/consul-template#1144] opened 2018-10-08 06:12 UTC
### Consul Template version
```
# consul-template --version
consul-template v0.19.5 (57b6c71)

vault --version
Vault v0.11.2+prem ('1356cc5f124a9f7fc7aa84cdabc36405c2353d41')
```

### Command

First generate a wrapped token using Vault agent.
```shell
/usr/local/bin/vault agent -config /etc/vault-agent.d/vault-agent.hcl ; \
  jq -r '.token' /mnt/ramdisk/token
==> Vault agent configuration:

                     Cgo: disabled
               Log Level: info
                 Version: Vault v0.11.2+prem
             Version Sha: 1356cc5f124a9f7fc7aa84cdabc36405c2353d41

==> Vault server started! Log data will stream in below:

2018-10-08T05:45:06.139Z [INFO ] sink.file: creating file sink
2018-10-08T05:45:06.140Z [INFO ] sink.file: file sink configured: path=/mnt/ramdisk/token
2018-10-08T05:45:06.142Z [INFO ] sink.server: starting sink server
2018-10-08T05:45:06.142Z [INFO ] auth.handler: starting auth handler
2018-10-08T05:45:06.142Z [INFO ] auth.handler: authenticating
2018-10-08T05:45:06.180Z [INFO ] auth.handler: authentication successful, sending token to sinks
2018-10-08T05:45:06.180Z [INFO ] auth.handler: starting renewal process
2018-10-08T05:45:06.199Z [INFO ] auth.handler: renewed auth token
2018-10-08T05:45:06.217Z [INFO ] sink.file: token written: path=/mnt/ramdisk/token
2018-10-08T05:45:06.217Z [INFO ] sink.server: sink server stopped
2018-10-08T05:45:06.217Z [INFO ] sinks finished, exiting
6NKQpLO3ozjRQiIMQmMehxvM
```
Unwrap the token, showing json response
```
# vault unwrap -format=json 6NKQpLO3ozjRQiIMQmMehxvM
{
  "request_id": "74c1c819-375c-7ab7-5631-d22a299cbcb9",
  "lease_id": "",
  "lease_duration": 0,
  "renewable": false,
  "data": {
    "token": "6xixcsnpVwvHirzEW0IThPgg"
  },
  "warnings": null
}
```
Create a regular wrapped token, unwrap and display json response
```
vault token create -wrap-ttl=5m
Key                              Value
---                              -----
wrapping_token:                  8MaLbGiTbVj7o4AKYYqFlQxC
wrapping_accessor:               fqAPoPuO4ED8TpQh4bixuULO
wrapping_token_ttl:              5m
wrapping_token_creation_time:    2018-10-08 05:46:48.681333704 +0000 UTC
wrapping_token_creation_path:    auth/token/create
wrapped_accessor:                76c2cxlWve1mRUFgJcrkSMsY
# vault unwrap -format=json 8MaLbGiTbVj7o4AKYYqFlQxC
{
  "request_id": "c2d04eea-6713-fb73-25ba-a945c3f2b9a2",
  "lease_id": "",
  "lease_duration": 0,
  "renewable": false,
  "data": null,
  "warnings": null,
  "auth": {
    "client_token": "3CPWwhVqrjiwpGoRyAOMbb6Q",
    "accessor": "76c2cxlWve1mRUFgJcrkSMsY",
    "policies": [
      "default",
      "vault-admin"
    ],
    "token_policies": [
      "default",
      "vault-admin"
    ],
    "identity_policies": null,
    "metadata": null,
    "lease_duration": 2764800,
    "renewable": true
  }
}
```

Generate wrapped token with Vault agent and attempt to unwrap with Consul-template
```
# /usr/local/bin/vault agent -config /etc/vault-agent.d/vault-agent.hcl ; \
  jq -r '.token' /mnt/ramdisk/token
==> Vault agent configuration:

                     Cgo: disabled
               Log Level: info
                 Version: Vault v0.11.2+prem
             Version Sha: 1356cc5f124a9f7fc7aa84cdabc36405c2353d41

==> Vault server started! Log data will stream in below:

2018-10-08T05:59:32.689Z [INFO ] sink.file: creating file sink
2018-10-08T05:59:32.689Z [INFO ] sink.file: file sink configured: path=/mnt/ramdisk/token
2018-10-08T05:59:32.692Z [INFO ] sink.server: starting sink server
2018-10-08T05:59:32.692Z [INFO ] auth.handler: starting auth handler
2018-10-08T05:59:32.692Z [INFO ] auth.handler: authenticating
2018-10-08T05:59:32.731Z [INFO ] auth.handler: authentication successful, sending token to sinks
2018-10-08T05:59:32.731Z [INFO ] auth.handler: starting renewal process
2018-10-08T05:59:32.748Z [INFO ] auth.handler: renewed auth token
2018-10-08T05:59:32.764Z [INFO ] sink.file: token written: path=/mnt/ramdisk/token
2018-10-08T05:59:32.764Z [INFO ] sink.server: sink server stopped
2018-10-08T05:59:32.764Z [INFO ] sinks finished, exiting
4D0bD62ZVvzRKuBF3SqN9hW5

# /usr/local/bin/consul-template -config=/etc/consul-template.d \
  -vault-token=4D0bD62ZVvzRKuBF3SqN9hW5 \
  -vault-ssl-verify=false -vault-unwrap-token
2018/10/08 06:00:22.829726 [WARN] (clients) disabling vault SSL verification
2018/10/08 06:00:22.848326 [ERR] (cli) runner: runner: client set: vault unwrap: no secret auth
```
### Expected behavior

Consul-template should unwrap the Vault token and daemonize

### Actual behavior

Consul-template erred out with the following output:
```
2018/10/08 06:00:22.829726 [WARN] (clients) disabling vault SSL verification
2018/10/08 06:00:22.848326 [ERR] (cli) runner: runner: client set: vault unwrap: no secret auth
```
Looks like the data structure that a wrapped token generated by Vault agent is of a different format than that of a regular token.
See here https://github.com/hashicorp/consul-template/blob/master/dependency/client_set.go#L273 for the fields parsed.

**Comment by eikenb** [comment] 2019-08-07 23:51
Hey @greenbrian, thanks for the report and sorry for the long delay in a response.

I'm not able to reproduce this, though I'm not 100% I'm replicating what you did as you didn't post the contents of the vault-agent.hcl or the consul-template configuration. Here's what I used...
```
#!/bin/sh

unwrapped=$(vault token create -ttl=2m -format=json \
    | jq -r '.auth.client_token')
export VAULT_TOKEN=$unwrapped
export VAULT_ADDR='http://127.0.0.1:8200'

wrapped=$(vault token create -ttl=1m -wrap-ttl=1m -format=json \
    | jq -r '.wrap_info.token')

echo "Token: $wrapped"

cat > foo.ctmpl << EOF
: {{ key "foo" }}
EOF

consul kv put foo "hello world"

log=warn
[ -n "$1" ] && log="$1"
consul-template \
    -template "foo.ctmpl:foo" \
    -log-level $log \
    -vault-token="$wrapped" \
    -vault-ssl-verify=false \
    -vault-unwrap-token \
    -once

rm -vf foo
```
Which had the output...
```
[~]./runme
Token: s.UclGGEKLM1t7l1h7cv4Wv4wE
Success! Data written to: foo
2019/08/07 23:49:51.951620 [WARN] (clients) disabling vault SSL verification
removed 'foo'
```

Do you still see this issue? Maybe it was resolved between 0.19.5 and now?

**Comment by jamesandariese** [comment] 2022-01-22 21:24
First, if you've landed here because you're getting this error:

Check if you're wrapping your token in the sink instead of the auth method while using `exit_after_auth`/`-exit-after-auth`.

If you're using it in the sink, move it to the method and try again.

Now my $.02 on the error itself (unsure if it's a bug at all so I won't call it that)

I see this issue when using the following config:
```
vault {
    address = "https://vault.service.consul:8200"
    ca_path = "/ca-certificates"
}

auto_auth {
    method {
        type = "approle"
        config = {
            role_id_file_path = "/approle/role_id"
            secret_id_file_path = "/approle/secret_id"
            remove_secret_id_file_after_reading = false
        }
    }
    sink {
        type = "file"
        config = {
            path = "/vault-agent-token-wrapping.json"
        }
        wrap_ttl = "30s"
    }
}
```

I do not see it with the following:
```
vault {
    address = "https://vault.service.consul:8200"
    ca_path = "/ca-certificates"
}

auto_auth {
    method {
        type = "approle"
        config = {
            role_id_file_path = "/approle/role_id"
            secret_id_file_path = "/approle/secret_id"
            remove_secret_id_file_after_reading = false
        }
        wrap_ttl = "30s"
    }
    sink {
        type = "file"
        config = {
            path = "/vault-agent-token-wrapping.json"
        }
    }
}
```

With the non-working config, the returned JSON (serialized SecretWrapInfo) looks like this:
```
{"token":"s.z2JxGEub8VdvZwsGcnuvO4RR","accessor":"3aHVUAYkJfQLHZRAoGXfo50E","ttl":30,"creation_time":"2022-01-22T21:02:17.072594941Z","creation_path":"sys/wrapping/wrap","wrapped_accessor":""}
```

Note the blank wrapped_accessor.  [The docs for SecretWrapInfo](https://pkg.go.dev/github.com/hashicorp/vault/api#SecretWrapInfo) indicates that this means there is no token wrapped which seems consistent with "no secret auth" meaning that there's no wrapped token.

This happens for me when using `-exit-after-auth`.

In my case, I didn't need to do the wrapping in the sink and the error stopped happening when I moved it to the method instead where it actually belongs (it shouldn't ever be wrapped in the sink for `-exit-after-auth` because the agent won't be running to renew the token anyway).

Also, this appears to be an issue with vault agent, not consul-template, which is why it wasn't reproduced when using `vault token create` instead of `vault agent`.

I would still expect the sink to be able to wrap the token successfully but if this only happens with the combination of `-exit-after-auth` and `wrap_ttl` in the sink, then simply documenting that this combination is forbidden and possibly programmatically forbidding it with an error that leads the operator to a solution would be a great resolution here.

Based on the "Command" section of the original report, it looks safe to assume that @greenbrian was also using `-exit-after-auth` via `exit_after_auth` in the config file referenced.

**Comment by eikenb** [comment] 2022-02-01 01:40
I'm going to look into this as part of 0.28.0. The result should *at least* be a documentation update if I can't get sink wrap_ttl fixed.

**Comment by eikenb** [comment] 2022-04-05 21:10
There is really nothing to be done on the consul-template side of things from what I can tell. I filed a ticket with the Vault project referencing this one. Remember to read @jamesandariese comment for a workaround if you are seeing this issue.

**Closed by eikenb** 2022-04-05 21:10 UTC
Labels: bug, docs, vault

**Comment by eikenb** [comment] 2022-04-05 23:21
Github tracks the references, but here's the link to the Vault issue I filed for subscribers.

https://github.com/hashicorp/vault/issues/14926
