### ISSUE TITLE
function "keyExists" not defined

### ISSUE THREAD

**Issue by tangjiaxing669** [hashicorp/consul-template#828] opened 2016-12-22 07:20 UTC
```shell
[root@master711 Test]# curl -sSLXGET http://localhost:8500/v1/kv/web?recurse | python -m json.tool
[
    {
        "CreateIndex": 17,
        "Flags": 0,
        "Key": "web/key1",
        "LockIndex": 0,
        "ModifyIndex": 17,
        "Value": "dGVzdA=="
    },
    {
        "CreateIndex": 18,
        "Flags": 42,
        "Key": "web/key2",
        "LockIndex": 0,
        "ModifyIndex": 18,
        "Value": "dGVzdA=="
    },
    {
        "CreateIndex": 20,
        "Flags": 0,
        "Key": "web/sub/key3",
        "LockIndex": 0,
        "ModifyIndex": 20,
        "Value": "dGVzdA=="
    }
]
[root@master711 Test]# curl -sSLXGET http://localhost:8500/v1/catalog/services | python -m json.tool
{
    "consul": []
}
[root@master711 Test]# curl -sSLXGET http://localhost:8500/v1/catalog/nodes | python -m json.tool
[
    {
        "Address": "172.30.16.35",
        "CreateIndex": 4,
        "ModifyIndex": 5,
        "Node": "master711",
        "TaggedAddresses": {
            "lan": "172.30.16.35",
            "wan": "172.30.16.35"
        }
    },
    {
        "Address": "172.30.16.124",
        "CreateIndex": 7,
        "ModifyIndex": 8,
        "Node": "master712",
        "TaggedAddresses": {
            "lan": "172.30.16.124",
            "wan": "172.30.16.124"
        }
    }
]
[root@master711 Test]# 
```

This test. have three keys. 

```shell
[root@master711 Test]# cat test.ctmpl 
{{range node}}
  {{if keyExists .Node@datacenter1}}
    {{.Node}} = {{.Address}}
  {{else}}
    {{keyOrDefault $Node := "Jason tom"}}
    {{.Node}}
{{end}}
[root@master711 Test]# 
```

This my template file. 

When i start the consul-template, i throw the following exception:

```
[root@master711 Test]# consul-template -consul localhost:8500 -template "/root/Test/test.ctmpl:/root/Test/result.conf"
Consul Template returned errors:
template: template: test.ctmpl:1: function "keyExists" not defined
...
[root@master711 Test]# consul-template -consul localhost:8500 -template "/root/Test/test.ctmpl:/root/Test/result.conf"
Consul Template returned errors:
template: template: test.ctmpl:2: function "keyOrDefault" not defined
```

I don't know why, please help me.

**Comment by jippi** [comment] 2016-12-22 07:25
use `key_or_default` - the master README contains features your version don't have

pick the right tag ( https://github.com/hashicorp/consul-template/releases ) for your version and look at the README for that release

**Comment by tangjiaxing669** [comment] 2016-12-22 07:49
@jippi thank you very much.

```
[root@master711 Test]# consul-template -v
consul-template v0.16.0
[root@master711 Test]# 
```

This my `consul-template` version. I did not find the function you said `key_or_default`.

**Comment by jippi** [comment] 2016-12-22 08:37
@tangjiaxing669 please see https://github.com/hashicorp/consul-template/tree/v0.16.0#key_or_default :)

**Comment by tangjiaxing669** [comment] 2016-12-22 08:48
@jippi thank you very much.

**Comment by sethvargo** [comment] 2016-12-22 22:09
Dupe of #822

**Closed by sethvargo** 2016-12-22 22:09 UTC
