### ISSUE TITLE
parseUint invalid syntax

### ISSUE THREAD

**Issue by nugend** [hashicorp/consul-template#609] opened 2016-04-16 00:57 UTC
This *seems* like a bug, but I'm still pretty new to the go template language, so maybe I'm just doing something wrong.

I have the value `50900` in my consul agent at `cfg/gateway/port`
I have the following lines in my template (I was trying to figure out the bug):
```
numprocs_start = {{key "cfg/gateway/port" | parseInt | add 1}}
numprocs_start = {{key "cfg/gateway/port"}}
numprocs_start = {{parseUint "50900"}}
numprocs_start = {{parseUint (key "cfg/gateway/port") | add 1}}
```
If I remove the last line, consul-template is perfectly happy spitting out

```
numprocs_start = 50901
numprocs_start = 50900
numprocs_start = 50900
```
With the last line present, I get the following error `<parseUint (key "cfg/...>: error calling parseUint: parseUint: strconv.ParseUint: parsing "": invalid syntax`

I also tried the last line as `numprocs_start = {{key "cfg/gateway/port" | parseUint}}` in which case I get the slightly different error `<parseUint>: error calling parseUint: parseUint: strconv.ParseUint: parsing "": invalid syntax`

I can work around this by just using `parseInt`, but this value shouldn't be negative.

I feel like I have to have blatantly missed something because it doesn't seem to be an issue with the value that is being returned for the key in question.

I also have other uses of `parseUint` in the template, but none pipelined directly with the `key` command

**Comment by sean-** [comment] 2016-04-16 20:02
Hi @nugend.  I was able to reproduce your issue on `v0.14.0`, however I was not able to on `master`.  Can you update to `master` (`go get -u github.com/hashicorp/consul-template`)?  I've included the following output from `master` below.

```
% ./bin/consul-template -version
consul-template v0.15.0-dev (5b955a8999a29b01e301cc9b9ac7c4b7b714685f+CHANGES)
% curl -X PUT -d '41' -H "X-Consul-Token: masterToken" 'http://127.0.0.1:8500/v1/kv/test/key1'
true
% curl -X GET -H "X-Consul-Token: masterToken" 'http://127.0.0.1:8500/v1/kv/test/key1?pretty'
[
    {
        "LockIndex": 0,
        "Key": "test/key1",
        "Flags": 0,
        "Value": "NDE=",
        "CreateIndex": 4133,
        "ModifyIndex": 4137
    }
]
% cat foo.tmpl
{{ parseUint "" | add 1}}
{{ parseUint "50990" | add 1}}
{{ key "test/key1" | parseUint | add 1 }}
{{ parseUint (key "test/key1") | add 1 }}
% ./bin/consul-template -once -template="foo.tmpl:foo.txt"
% cat foo.txt
1
50991
42
42
```

I'm going to close this ticket for now since you have a workaround and and it looks like it's been fixed for the next release. Thank you for the report!

**Closed by sean-** 2016-04-16 20:02 UTC
