### ISSUE TITLE
range service with dynamic service name and tag error since v 0.18

### ISSUE THREAD

**Issue by bhuisgen** [hashicorp/consul-template#860] opened 2017-01-25 15:21 UTC
Something changed with range service and dynamic service and tag since v 0.18.

### Consul Template version

```
consul-template v0.18.0 (5211c66)
```

### Configuration

```liquid
{{$name := env "SERVICE_NAME"}}
{{$tag := env "SERVICE_TAG"}}
{{range service (print $tag "." $name)}}
   server {{.Address}}:{{.Port}};
{{end}}
```

### Debug output

```
/etc/consul-template/templates/test.ctmpl: execute: template: :6:8: executing "" at <service (print $tag ...>: error calling service: health.service: invalid format: "."
```

This template works with previous versions but not with v 0.18. To fix this error I need to extra check $tag and $service like this:

```liquid
{{$name := env "SERVICE_NAME"}}
{{$tag := env "SERVICE_TAG"}}
# {{$name}}
# {{$tag}}

{{if and $name $tag}}
{{range service (print $tag "." $name)}}
   server {{.Address}}:{{.Port}};
{{end}}
{{end}}
```

Is this kind of check mandatory now ? Is it required to do the same with all other functions ?

### References
- #857 
- #801

**Comment by sethvargo** [comment] 2017-02-06 17:29
Hi @bhuisgen 

Thank you for opening an issue. This is a duplicate of https://github.com/hashicorp/consul-template/issues/879. Please see my explanation and recommended solution on that ticket. Sorry about that!

**Closed by sethvargo** 2017-02-06 17:29 UTC
