### ISSUE TITLE
Consul template restart issue k8s

### ISSUE THREAD

**Issue by imvishalvyas** [hashicorp/consul-template#1325] opened 2019-12-11 06:22 UTC
We are using vault on kubernetes and it's auto unsealed. Our apps also deployed on different kubernetes clusters. Now some of the apps suddenly restarted due to consul template terminated. here are the logs. After delete the pod application up again and works fine. What are the cause of the issue.

### Consul Template version

hashicorp/consul-template:latest

Stack driver Error logs : 
```

E 2019-12-11T03:33:26.936522796Z 2019/12/11 03:33:26.936210 [WARN] vault.read(secret/kubernetes/cluster/prod/ory/config): failed to check if secret/kubernetes/cluster/prod/ory/config is KVv2, assume not: Error making API request.
 
 
E 2019-12-11T03:33:26.936652295Z URL: GET https://my-vault.com:8200/v1/sys/internal/ui/mounts/secret/kubernetes/cluster/prod/ory/config
 
E 2019-12-11T03:33:26.936657430Z Code: 403. Errors:
 
 
E 2019-12-11T03:33:26.936666926Z * permission denied
 
E 2019-12-11T03:33:26.949976594Z 2019/12/11 03:33:26.949782 [WARN] (view) vault.read(secret/kubernetes/cluster/prod/ory/config): vault.read(secret/kubernetes/cluster/prod/ory/config): Error making API request.
  
E 2019-12-11T03:33:26.950025668Z URL: GET https://my-vault.com:8200/v1/secret/kubernetes/cluster/prod/ory/config
 
E 2019-12-11T03:33:26.950029914Z Code: 403. Errors:
 
```

**Comment by eikenb** [comment] 2019-12-11 23:42
Hey @imvishalvyas, sorry for your troubles.

That looks like your vault token has expired. I can reproduce something similar locally by calling consul-template with `-vault-renew-token=false` and waiting for the token's TTL to expire. So check to make sure your vault token is good and either getting renewed automatically or being updated by another external system.

Note that we use github issues for bugs and feature requests, for questions you'll likely get more/better responses by posting to the community forum: https://discuss.hashicorp.com/c/consul

Thanks.

**Comment by eikenb** [comment] 2019-12-19 20:43
I'm going to close this out as I answered as well as I can. If you still need help with this please consider trying the forum. Thanks.

**Closed by eikenb** 2019-12-19 20:43 UTC
Labels: question
