### ISSUE TITLE
Walking a nested tree

### ISSUE THREAD

**Issue by pdf** [hashicorp/consul-template#243] opened 2015-04-04 11:15 UTC
As an exercise I'd like to generate `/etc/network/interfaces` on a Debian system.  A simple example of the structure might look like:

```
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp
iface eth0 inet6 dhcp
  accept_ra 1
  autoconf 0
```

I'm struggling to represent this in consul's KV store in a way that can be templated by consul-template.  My first inclination was to create a structure like:

```
/network/lo/inet/loopback = null
/network/eth0/inet/dhcp = null
/network/eth0/inet6/dhcp/accept_ra = 1
/network/eth0/inet6/dhcp/autoconf = 0
```
[gist: http://localhost:8500/v1/kv/network/?recurse](https://gist.github.com/pdf/914d3a2e4c1cdff401fa)

Then walk the structure using `range`, `tree`, and `byKey`.  But `byKey` only appears to be suited to a single level of nesting, and there doesn't appear to be any way to traverse the structure without getting really ugly and generating a bunch of queries/watches all the way down the chain.

Am I missing something obvious here?

**Comment by sethvargo** [comment] 2015-04-29 15:25
Hi there,

Even though this issue was created first, I didn't see it until later. This is actually a duplicate of #258 - since there is more information on that issue, let's track that please :smile:. Thanks!

**Closed by sethvargo** 2015-04-29 15:25 UTC
