### ISSUE TITLE
Consul Template getting stuck

### ISSUE THREAD

**Issue by jippi** [hashicorp/consul-template#597] opened 2016-03-29 07:23 UTC
Hi!

This may or may not be relevant to https://github.com/hashicorp/vault/issues/1257 

The configuration files are 100% the same: https://dl.dropboxusercontent.com/u/27514/hashicorp-debug.tar

For some reason, consul-template seem to get "stuck" once in awhile, seem to happen after I started to use Vault secrets in my template(s).

There are no errors in Consul, CT or Vault that seem to reveal anything interesting

My use case:

Vault secret(s) using a default `generic` backend and a `mysql` backend - those will be written to nginx and other config files as `fastcgi` ENVs for our php-fpm backend(s).

The last output from CT:

```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
Reloading nginx configuration: nginx.
```

The last output from Vault

```
2016/03/28 13:01:02 [INFO] expire: revoked 'mysql/creds/frontend_main/9c752080-3b94-a944-05da-532d57bda31b'
2016/03/28 14:04:49 [INFO] expire: revoked 'mysql/creds/frontend_test/53aaed2c-233e-1e8f-e486-90e5bb0c756f'
2016/03/28 14:04:49 [INFO] expire: revoked 'mysql/creds/frontend_main/128afe3a-99df-9bca-d820-f6eb7e84bcc1'
2016/03/28 14:15:49 [INFO] expire: revoked 'mysql/creds/frontend_test/186dcce0-8632-2e02-1f5d-c80cc63c54a9'
2016/03/28 14:15:49 [INFO] expire: revoked 'mysql/creds/frontend_main/e81baa1c-cb9d-5cfd-6085-1e5ea67d3a21'
2016/03/28 14:24:48 [INFO] expire: revoked 'mysql/creds/frontend_test/68a99e50-093c-0866-422a-21daee32cc18'
2016/03/28 14:24:48 [INFO] expire: revoked 'mysql/creds/frontend_main/8bdd259d-6f0f-bced-e639-b1af36dc44fb'
2016/03/28 14:58:48 [INFO] expire: revoked 'mysql/creds/frontend_test/9fd7fc45-9b72-52fe-f88a-b6e59189f3f4'
2016/03/28 14:58:48 [INFO] expire: revoked 'mysql/creds/frontend_main/78958691-845f-9872-d281-58d96ee73a1e'
```

There doesn't seem to be any file-handle craziness going on as the original Vault ticket, things just "freeze" up.

Currently the processes have been running for ~21 hour, and the mysql secret lease got a lease time configured as follow:

```
-> vault read mysql/config/lease
Key      	Value
lease    	1h0m0s
lease_max	24h0m0s
```

which, afaik should cause CT to refresh any leases every ~12h (half of the max-lifetime) - but that doesn't seem to happen - this morning when I got in, the app used some revoked credentials and thus the app failed completely

The configuration file in question got the following `stat` output

```
-> stat /etc/nginx/sites-enabled/20-frontend
  File: `/etc/nginx/sites-enabled/20-frontend'
  Size: 11215     	Blocks: 24         IO Block: 4096   regular file
Device: 901h/2305d	Inode: 3675505     Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-03-28 14:06:57.653368995 +0000
Modify: 2016-03-28 14:06:57.613368599 +0000
Change: 2016-03-28 14:06:57.625368718 +0000
 Birth: -
```

When trying to `strace` some Vault threads, I noticed this repeated in 4-5 of the threads running - not sure if its relevant or not

![image](https://cloud.githubusercontent.com/assets/22841/14100642/3d9873d6-f58f-11e5-8483-8b80c6976e6b.png)

Both Vault and Consul seem to be up and responding to any kind of API requests I throw at it as well

One thing worth mentioning, mysql seem to have restarted, it has an uptime of `10441 seconds` this morning - could it be a case where Vault / CT does not handle that case very well? 

Or shouldn't CT at least time out or give some kind of error that it failed to talk to Vault within due time?

Restarting `Vault` does not seem to do anything for the problem
Restarting CT did seem to do the trick though (after restarting Vault)

Worth mentioning everything (Consul, CT and Vault) are running on the same server, which is firewalled, but not on loopback

**Comment by sethvargo** [comment] 2016-03-29 09:13
Hi @jippi,

Thank you for opening an issue. Can you share the Consul Template debug logs when this happens? Please share the template as well.

One thing I want to note:

> which, afaik should cause CT to refresh any leases every ~12h (half of the max-lifetime)

This is untrue. Consul Template renews at lease_duration/2.0, not lease_max/2.0, so it's going to renew every 30m. 

Are you doing any SIGHUP or reloading of the CT process? Can you show me the `lsof -p $CONSUL_TEMPLATE_PID` when this happens please?

> Shouldn't CT at least time out or give some kind of error that it failed to talk to Vault within due time?

This goes against the fundamental design of Consul Template. CT is designed to be highly fault tolerant. You can look in the logs and see warnings for connection failures, but CT is designed to run in distributed systems where failure is inevitable. It will continuously retry until it can establish the connection to Vault/Consul.

**Comment by jippi** [comment] 2016-03-29 13:24
@sethvargo I'm going to bump logging up to debug now and see what happens

For the files, they are in the tar bundle referenced in the ticket body ( https://dl.dropboxusercontent.com/u/27514/hashicorp-debug.tar ) - they include Consul + CT + Vault config (including templates and hcl for those templates)

We do a SIGHUP once in awhile (when we deploy, so it happens 20-30 times a day currently) - i checked lsof for both Consul, CT and Vault, nothing seemed out of the ordinary (<50 opened handles) - when it happens next time, I'll capture the output

**Comment by jefferai** [comment] 2016-03-29 14:25
@jippi It's entirely possible that the behavior you're seeing in the Vault ticket is also the root cause of this problem. Can we tackle that first and then see if this clears up?

**Comment by jippi** [comment] 2016-03-29 14:26
@jefferai sure, is there a debug log-level for Vault as well?

**Comment by jefferai** [comment] 2016-03-29 14:31
@jippi There is, although I don't think there's much that is output at that log level. Most things within Vault are either highly successful, or errors  :-)  So there are some warnings and some info, but little debug.

**Comment by sethvargo** [comment] 2016-04-23 02:43
This is fixed in master. We now close unused connections. I think the other issue is related to Vault. If the issue persists after the next release of both tools, we can always revisit this. Thanks! 😄

**Closed by sethvargo** 2016-04-23 02:43 UTC
