### ISSUE TITLE
Periods in service names

### ISSUE THREAD

**Issue by doubleyou** [hashicorp/consul-template#459] opened 2015-11-12 02:56 UTC
Basically, something like `{{service "my.service.in.my.domain.net" "any"}}` won't return anything, because of the tag syntax.

According to https://github.com/hashicorp/consul-template/blob/master/dependency/health_service.go#L173 it looks like there's not much that I can do aside from renaming the service, but maybe I'm missing something?

Thanks!

**Comment by doubleyou** [comment] 2015-11-12 02:58
Or, maybe, it makes sense to specify some recommended service name pattern.

**Comment by sethvargo** [comment] 2015-11-12 08:21
Hi @doubleyou 

Thank you for opening an issue. This is a duplicate of https://github.com/hashicorp/consul-template/issues/295. You can read more about why using services with dots/periods is discouraged from both Consul and Consul Template on that issue.

**Closed by sethvargo** 2015-11-12 08:21 UTC
