### ISSUE TITLE
Even when passed -ssl consul-template still calls the http endpoint instead of https

### ISSUE THREAD

**Issue by Telmo** [hashicorp/consul-template#416] opened 2015-10-08 14:47 UTC
Our consul cluster is set to only listen for https:

```
  "ports": {
    "http": -1,
    "https": 8500
  },
```

Even when given the `-ssl` flag consul template still tries to talk to `http`

```
# consul-template -ssl -ssl-cert ssl/consul.cert -ssl-ca-cert ssl/ca.cert -consul=consul-ch2-3p.sys.redacted.net:8500 -template="asl.ctmpl:asl.list"
2015/10/08 10:41:51 [DEBUG] (logging) setting up logging
2015/10/08 10:41:51 [DEBUG] (logging) config:

{
  "name": "consul-template",
  "level": "WARN",
  "syslog": false,
  "syslog_facility": "LOCAL0"
}

2015/10/08 10:41:51 [ERR] (view) "storeKeyPrefix(asl/services)" store key prefix: error fetching: Get http://consul-ch2-3p.sys.redacted.net:8500/v1/kv/asl/services?recurse=&wait=60000ms: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
2015/10/08 10:41:51 [ERR] (runner) watcher reported error: store key prefix: error fetching: Get http://consul-ch2-3p.sys.redacted.net:8500/v1/kv/asl/services?recurse=&wait=60000ms: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
2015/10/08 10:41:56 [ERR] (view) "storeKeyPrefix(asl/services)" store key prefix: error fetching: Get http://consul-ch2-3p.sys.redacted.net:8500/v1/kv/asl/services?recurse=&wait=60000ms: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
2015/10/08 10:41:56 [ERR] (runner) watcher reported error: store key prefix: error fetching: Get http://consul-ch2-3p.sys.redacted.net:8500/v1/kv/asl/services?recurse=&wait=60000ms: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
^CReceived interrupt, cleaning up..
```

**Comment by sethvargo** [comment] 2015-10-08 14:52
Hi @Telmo 

This is a duplicate of https://github.com/hashicorp/consul-template/issues/321 and has already been fixed. I will be releasing a new version soon.

**Closed by sethvargo** 2015-10-08 14:52 UTC

**Comment by Telmo** [comment] 2015-10-08 16:38
any ETA on the release?

**Comment by sethvargo** [comment] 2015-10-08 17:13
Today or tomorrow
