### ISSUE TITLE
Hostnames with dots render invalid format error

### ISSUE THREAD

**Issue by alkalinecoffee** [hashicorp/consul-template#977] opened 2017-07-12 19:45 UTC
Consul template should honor hostnames with periods, as consul does.

Given this template:

```
{{ with node "a.b" }}
```

Renders:
```
2017/07/12 19:41:06.235619 [ERR] (cli) template.tpl: execute: template: :5:8:
executing "" at <node "a.b">: error calling node: catalog.node: invalid format: "a.b"
```

Consul supports hostnames with periods, as does the API (`/v1/catalog/node/localhost.localdomain` is a valid request).

`consul-template v0.19.0 (33b34b3)`

**Comment by sethvargo** [comment] 2017-07-12 19:59
Hi there,

For services, this is a duplicate of #295, #459, #643, and #757. It is highly discouraged and may break in the future if you use dots due to the way DNS resolution works. However, I'm not sure how to behave for nodes.

@slackpad any ideas here?

**Closed** 2017-10-30 19:03 UTC
