### ISSUE TITLE
With "wait" consul-template spawns the child process before rendering the template

### ISSUE THREAD

**Issue by aryklein** [hashicorp/consul-template#1229] opened 2019-07-15 04:50 UTC
### Consul Template version
`consul-template v0.20.0`
(The same setup works fine in `consul-template v0.19.5`)

### Configuration

/etc/consul-template.conf:

```hcl
consul {
  address = "consul.query.consul:28500"
  retry {
    enabled = true
    attempts = 12
    backoff = "250ms"
    max_backoff = "1m"
  }
}
reload_signal = "SIGHUP"
kill_signal = "SIGINT"
log_level = "warn"
pid_file = "/var/run/consul-template/consul-template.pid"
exec {
  command = "/usr/local/bin/pgpool -n -D"
  kill_signal = "SIGINT"
  kill_timeout = "10s"
}
template {
  source = "/usr/local/etc/pgpool.conf.tpl"
  destination = "/usr/local/etc/pgpool.conf"
  wait {
    min = "5s"
    max = "10s"
  }
}
```

### Command

```shell
consul-template -config /etc/consul-template.conf
```

### Expected behavior

After the wait time, it should render the template and then spawn the child process.

### Actual behavior

It spawns the child process before rendering the template (only when you use `wait` in the `template` block). It seems that it executes the command in the `exec` block and then waits for rendering the template.

**Comment by eikenb** [comment] 2019-07-16 06:58
Hey @aryklein, thanks for reporting this issue.

I think this might be a duplicate of the issue fixed with #1227. So if you want to try out a build off the master branch I think it might already be fixed. If you get a chance to try, I'd appreciate hearing back if it is fixed or not.

Thanks.

**Comment by aryklein** [comment] 2019-07-17 05:10
Hey @eikenb, 

Sure thing. I was using the pre-compiled versions from here: https://releases.hashicorp.com/consul-template
Can you give me some instructions how to compile it from the master branch?

Thanks

**Comment by eikenb** [comment] 2019-07-18 20:59
To build the master branch you'd need a Go dev setup and then you could run `make dev` to build it locally.  But getting that all setup takes some work.

Thinking about it I'm not 100% this is a replication of that issue though. If you have a chance to spend some time on this I think, instead of doing the work to build it yourself, it'd be better if you could try to create a standalone, simple way to replicate the issue. Something I could run locally with minimal setup.

If you don't have time for that would you mind adding your template here so I have all the parts involved. It's hard to get a good idea of what's happening without all the setup.

Thanks.

**Comment by eikenb** [comment] 2019-07-25 23:49
I don't think this is a duplicate of #1227 as I'm able to reproduce it with a simple test using current master (that has the fix).

This (and a better understanding of the code) also makes me think that #1209 is a case of this same issue and not related to #1227.

**Comment by eikenb** [comment] 2019-07-26 23:15
Most obvious fix for this is to not have it setup the wait/quiescence timers until all templates have been rendered once. The most obvious way to do that is to move the quiescence initialization code down a few lines into the existing conditional block, conditional on allTemplateRendered().

I.E. Moving this chunk...
https://github.com/hashicorp/consul-template/blob/4170dc959829f008b9697248220255f9251ba0ca/manager/runner.go#L226-L247

To just after here...
https://github.com/hashicorp/consul-template/blob/4170dc959829f008b9697248220255f9251ba0ca/manager/runner.go#L257-L258

**Comment by aryklein** [comment] 2019-07-29 16:53
@eikenb thanks for taking care of this issue :+1:

**Closed** 2019-07-29 22:39 UTC
Labels: bug
