### ISSUE TITLE
Long running consul-template generate wrong output, a fresh running generates a proper one.

### ISSUE THREAD

**Issue by sielaq** [hashicorp/consul-template#198] opened 2015-02-17 20:17 UTC
I have a very strange issue, it was hard to duplicate, but finally I was able to.

To make it simpler I have 2 different services python1 and python2,
that i scale up and down, after juggling with them - scaling down to 0
and then scale up again, I saw that generating an out put was wrong - some instances of service were missing. So I decided to check an output from a new fresh consul-template (-dry -one) and it was correct.

services status (both with tag "webapp"):
python1 - only one instance running 
python2 - no instance running

template part:
```
... <static part>...

{{range services}}{{$service:=.Name}}{{range .Tags}}{{if or (eq . "webapp") (eq . "haproxy")}}
    acl acl_{{$service}} hdr(host) -i {{$service}}.service.consul
    use_backend backend_{{$service}} if acl_{{$service}}
{{end}}{{end}}{{end}}
{{range services}}{{$service:=.Name}}{{range .Tags}}{{if or (eq . "webapp") (eq . "haproxy")}}
    backend backend_{{$service}}
      balance leastconn
      option http-server-close
  {{range service $service "passing" }}    server {{.Name}} {{.Address}}:{{.Port}} maxconn 64
  {{end}}
{{end}}{{end}}{{end}}
```

GOOD OUTPUT: a fresh running consul-template -dry -once:
```
2015/02/17 19:52:36 [INFO] (runner) creating new runner (dry: true, once: true)
2015/02/17 19:52:36 [INFO] (runner) creating consul/api client
2015/02/17 19:52:36 [DEBUG] (runner) setting address to 10.44.211.35:8500
2015/02/17 19:52:36 [INFO] (runner) creating Watcher
2015/02/17 19:52:36 [INFO] (runner) starting
2015/02/17 19:52:36 [DEBUG] (runner) running initial templates
2015/02/17 19:52:36 [INFO] (runner) running
2015/02/17 19:52:36 [DEBUG] (runner) checking template in.conf
2015/02/17 19:52:36 [INFO] (brain) getting data for catalog services
2015/02/17 19:52:36 [INFO] (brain) getting data for catalog services
2015/02/17 19:52:36 [INFO] (runner) was not watching 1 dependencies
2015/02/17 19:52:36 [INFO] (watcher) adding catalog services
2015/02/17 19:52:36 [DEBUG] (watcher) catalog services starting
2015/02/17 19:52:36 [INFO] (runner) updating dependencies
2015/02/17 19:52:36 [DEBUG] (view) catalog services starting fetch
2015/02/17 19:52:36 [DEBUG] (catalog services) querying Consul with &{Datacenter: AllowStale:false RequireConsistent:false WaitIndex:0 WaitTime:1m0s Token:}
2015/02/17 19:52:36 [DEBUG] (catalog services) Consul returned 6 catalog services
2015/02/17 19:52:36 [INFO] (view) catalog services received data from consul
2015/02/17 19:52:36 [DEBUG] (runner) receiving dependency catalog services
2015/02/17 19:52:36 [INFO] (brain) remembering catalog services
2015/02/17 19:52:36 [INFO] (runner) running
2015/02/17 19:52:36 [DEBUG] (runner) checking template in.conf
2015/02/17 19:52:36 [INFO] (brain) getting data for catalog services
2015/02/17 19:52:36 [INFO] (brain) getting data for catalog services
2015/02/17 19:52:36 [INFO] (brain) getting data for service "python1 [passing]"
2015/02/17 19:52:36 [INFO] (runner) was not watching 1 dependencies
2015/02/17 19:52:36 [INFO] (watcher) adding service "python1 [passing]"
2015/02/17 19:52:36 [DEBUG] (watcher) service "python1 [passing]" starting
2015/02/17 19:52:36 [INFO] (runner) updating dependencies
2015/02/17 19:52:36 [DEBUG] (runner) checking if catalog services still needed
2015/02/17 19:52:36 [DEBUG] (runner) catalog services is still needed
2015/02/17 19:52:36 [DEBUG] (view) service "python1 [passing]" starting fetch
2015/02/17 19:52:36 [DEBUG] (service "python1 [passing]") querying Consul with &{Datacenter: AllowStale:false RequireConsistent:false WaitIndex:0 WaitTime:1m0s Token:}
2015/02/17 19:52:36 [DEBUG] (service "python1 [passing]") Consul returned 1 services
2015/02/17 19:52:36 [DEBUG] (service "python1 [passing]") 1 services after health check status filtering
2015/02/17 19:52:36 [INFO] (view) service "python1 [passing]" received data from consul
2015/02/17 19:52:36 [DEBUG] (runner) receiving dependency service "python1 [passing]"
2015/02/17 19:52:36 [INFO] (brain) remembering service "python1 [passing]"
2015/02/17 19:52:36 [INFO] (runner) running
2015/02/17 19:52:36 [DEBUG] (runner) checking template in.conf
2015/02/17 19:52:36 [INFO] (brain) getting data for catalog services
2015/02/17 19:52:36 [INFO] (brain) getting data for catalog services
2015/02/17 19:52:36 [INFO] (brain) getting data for service "python1 [passing]"
2015/02/17 19:52:36 [INFO] (brain) checking if service "python1 [passing]" has data
2015/02/17 19:52:36 [DEBUG] (brain) service "python1 [passing]" had data
2015/02/17 19:52:36 [INFO] (brain) checking if catalog services has data
2015/02/17 19:52:36 [DEBUG] (brain) catalog services had data
2015/02/17 19:52:36 [DEBUG] (runner) checking ctemplate &{Source:in.conf Destination:/etc/haproxy/haproxy.cfg Command:}
> /etc/haproxy/haproxy.cfg
global
    log 127.0.0.1   local0
    log 127.0.0.1   local1 notice
    daemon
    maxconn 8192
    ulimit-n 65536
    nbproc  2

defaults
    mode http
    timeout connect 5000ms
    timeout client 60000ms
    timeout server 60000ms
    option forwardfor
    option httplog
    option dontlognull
    option forwardfor
    option http-server-close
    option redispatch
    stats enable
    stats uri /haproxyStats
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

listen stats :81
    mode http
    stats enable
    stats hide-version
    stats realm Haproxy\ Statistics
    stats uri /

frontend http-in
    bind *:80


    acl acl_python1 hdr(host) -i python1.service.consul
    use_backend backend_python1 if acl_python1


    backend backend_python1
      balance leastconn
      option http-server-close
      server python1 10.44.211.35:31000 maxconn 64


2015/02/17 19:52:36 [DEBUG] (runner) rendered: true
2015/02/17 19:52:36 [INFO] (runner) updating dependencies
2015/02/17 19:52:36 [DEBUG] (runner) checking if catalog services still needed
2015/02/17 19:52:36 [DEBUG] (runner) catalog services is still needed
2015/02/17 19:52:36 [DEBUG] (runner) checking if service "python1 [passing]" still needed
2015/02/17 19:52:36 [DEBUG] (runner) service "python1 [passing]" is still needed
2015/02/17 19:52:36 [INFO] (runner) once mode and all templates rendered
2015/02/17 19:52:36 [INFO] (runner) stopping
2015/02/17 19:52:36 [INFO] (watcher) stopping all views
2015/02/17 19:52:36 [DEBUG] (watcher) stopping catalog services
2015/02/17 19:52:36 [DEBUG] (watcher) stopping service "python1 [passing]"
```
BAD OUTPUT:  from a long running consul-template:

```
2015/02/17 19:48:52 [DEBUG] (catalog services) querying Consul with &{Datacenter: AllowStale:false RequireConsistent:false WaitIndex:761 WaitTime:1m0s Token:}
haproxy_configurator stderr | 2015/02/17 19:48:56 [DEBUG] (service "python2 [passing]") Consul returned 0 services
2015/02/17 19:48:56 [DEBUG] (service "python2 [passing]") 0 services after health check status filtering
2015/02/17 19:48:56 [DEBUG] (view) service "python2 [passing]" no new data (contents were the same)
2015/02/17 19:48:56 [DEBUG] (service "python2 [passing]") querying Consul with &{Datacenter: AllowStale:false RequireConsistent:false WaitIndex:762 WaitTime:1m0s Token:}
haproxy_configurator stderr | 2015/02/17 19:48:56 [DEBUG] (catalog services) Consul returned 6 catalog services
2015/02/17 19:48:56 [DEBUG] (view) catalog services no new data (contents were the same)
2015/02/17 19:48:56 [DEBUG] (catalog services) querying Consul with &{Datacenter: AllowStale:false RequireConsistent:false WaitIndex:762 WaitTime:1m0s Token:}
haproxy_configurator stderr | 2015/02/17 19:49:03 [DEBUG] (service "python2 [passing]") Consul returned 0 services
2015/02/17 19:49:03 [DEBUG] (service "python2 [passing]") 0 services after health check status filtering
2015/02/17 19:49:03 [DEBUG] (view) service "python2 [passing]" no new data (contents were the same)
2015/02/17 19:49:03 [DEBUG] (service "python2 [passing]") querying Consul with &{Datacenter: AllowStale:false RequireConsistent:false WaitIndex:763 WaitTime:1m0s Token:}
2015/02/17 19:49:03 [DEBUG] (catalog services) Consul returned 6 catalog services
2015/02/17 19:49:03 [DEBUG] (view) catalog services no new data (contents were the same)
2015/02/17 19:49:03 [DEBUG] (catalog services) querying Consul with &{Datacenter: AllowStale:false RequireConsistent:false WaitIndex:763 WaitTime:1m0s Token:}
haproxy_configurator stderr | 2015/02/17 19:50:03 [DEBUG] (catalog services) Consul returned 6 catalog services
2015/02/17 19:50:03 [DEBUG] (view) catalog services no new data (index was the same)
2015/02/17 19:50:03 [DEBUG] (catalog services) querying Consul with &{Datacenter: AllowStale:false RequireConsistent:false WaitIndex:763 WaitTime:1m0s Token:}
haproxy_configurator stderr | 2015/02/17 19:50:03 [DEBUG] (service "python2 [passing]") Consul returned 0 services
2015/02/17 19:50:03 [DEBUG] (service "python2 [passing]") 0 services after health check status filtering
2015/02/17 19:50:03 [DEBUG] (view) service "python2 [passing]" no new data (index was the same)
2015/02/17 19:50:03 [DEBUG] (service "python2 [passing]") querying Consul with &{Datacenter: AllowStale:false RequireConsistent:false WaitIndex:763 WaitTime:1m0s Token:}
haproxy_configurator stderr | 2015/02/17 19:51:03 [DEBUG] (catalog services) Consul returned 6 catalog services
2015/02/17 19:51:03 [DEBUG] (view) catalog services no new data (index was the same)
2015/02/17 19:51:03 [DEBUG] (catalog services) querying Consul with &{Datacenter: AllowStale:false RequireConsistent:false WaitIndex:763 WaitTime:1m0s Token:}
haproxy_configurator stderr | 2015/02/17 19:51:03 [DEBUG] (service "python2 [passing]") Consul returned 0 services
2015/02/17 19:51:03 [DEBUG] (service "python2 [passing]") 0 services after health check status filtering
2015/02/17 19:51:03 [DEBUG] (view) service "python2 [passing]" no new data (index was the same)
2015/02/17 19:51:03 [DEBUG] (service "python2 [passing]") querying Consul with &{Datacenter: AllowStale:false RequireConsistent:false WaitIndex:763 WaitTime:1m0s Token:}
haproxy_configurator stderr | 2015/02/17 19:51:19 [DEBUG] (service "python2 [passing]") Consul returned 0 services
2015/02/17 19:51:19 [DEBUG] (service "python2 [passing]") 0 services after health check status filtering
2015/02/17 19:51:19 [DEBUG] (view) service "python2 [passing]" no new data (contents were the same)
2015/02/17 19:51:19 [DEBUG] (service "python2 [passing]") querying Consul with &{Datacenter: AllowStale:false RequireConsistent:false WaitIndex:767 WaitTime:1m0s Token:}
2015/02/17 19:51:19 [DEBUG] (catalog services) Consul returned 6 catalog services
2015/02/17 19:51:19 [DEBUG] (view) catalog services no new data (contents were the same)
2015/02/17 19:51:19 [DEBUG] (catalog services) querying Consul with &{Datacenter: AllowStale:false RequireConsistent:false WaitIndex:767 WaitTime:1m0s Token:}
haproxy_configurator stderr | 2015/02/17 19:51:19 [DEBUG] (catalog services) Consul returned 6 catalog services
2015/02/17 19:51:19 [DEBUG] (view) catalog services no new data (contents were the same)
2015/02/17 19:51:19 [DEBUG] (catalog services) querying Consul with &{Datacenter: AllowStale:false RequireConsistent:false WaitIndex:769 WaitTime:1m0s Token:}
2015/02/17 19:51:19 [DEBUG] (service "python2 [passing]") Consul returned 0 services
2015/02/17 19:51:19 [DEBUG] (service "python2 [passing]") 0 services after health check status filtering
2015/02/17 19:51:19 [DEBUG] (view) service "python2 [passing]" no new data (contents were the same)
2015/02/17 19:51:19 [DEBUG] (service "python2 [passing]") querying Consul with &{Datacenter: AllowStale:false RequireConsistent:false WaitIndex:769 WaitTime:1m0s Token:}
haproxy_configurator stderr | 2015/02/17 19:52:19 [DEBUG] (service "python2 [passing]") Consul returned 0 services
2015/02/17 19:52:19 [DEBUG] (service "python2 [passing]") 0 services after health check status filtering
2015/02/17 19:52:19 [DEBUG] (view) service "python2 [passing]" no new data (index was the same)
2015/02/17 19:52:19 [DEBUG] (service "python2 [passing]") querying Consul with &{Datacenter: AllowStale:false RequireConsistent:false WaitIndex:769 WaitTime:1m0s Token:}
haproxy_configurator stderr | 2015/02/17 19:52:19 [DEBUG] (catalog services) Consul returned 6 catalog services
2015/02/17 19:52:19 [DEBUG] (view) catalog services no new data (index was the same)
2015/02/17 19:52:19 [DEBUG] (catalog services) querying Consul with &{Datacenter: AllowStale:false RequireConsistent:false WaitIndex:769 WaitTime:1m0s Token:}
haproxy_configurator stderr | 2015/02/17 19:53:19 [DEBUG] (catalog services) Consul returned 6 catalog services
2015/02/17 19:53:19 [DEBUG] (view) catalog services no new data (index was the same)
2015/02/17 19:53:19 [DEBUG] (catalog services) querying Consul with &{Datacenter: AllowStale:false RequireConsistent:false WaitIndex:769 WaitTime:1m0s Token:}
2015/02/17 19:53:19 [DEBUG] (service "python2 [passing]") Consul returned 0 services
2015/02/17 19:53:19 [DEBUG] (service "python2 [passing]") 0 services after health check status filtering
````
which generate config like:
```
...<static part>...


    acl acl_python1 hdr(host) -i python1.service.consul
    use_backend backend_python1 if acl_python1


    backend backend_python1
      balance leastconn
      option http-server-close
```

**Comment by sethvargo** [comment] 2015-02-17 22:47
Hi @sielaq 

I am sorry you are having problems with Consul Template. Are you able to provide more log output from the "long running" CT process? There is not enough log output there to adequately diagnose the issue.

**Comment by sethvargo** [comment] 2015-02-17 23:31
Also @sielaq, what version of Consul Template are you using?

**Comment by sethvargo** [comment] 2015-02-18 01:03
Hi @sielaq,

I spent a few hours today trying to debug and reproduce your issue, but I am afraid neither myself nor @ryanuber were able to come up with a reproduction case. 

The closest I was able to come was to force-failing the python1 service with a TTL expiration, but that is the expected behavior in this case. Are you able to supply any additional information? It would be especially helpful if you could provide a script that illustrates the problem, because it is still a bit unclear from the original issue description what the issue is.

**Comment by jimmcslim** [comment] 2015-02-18 02:16
I believe I am having a similar issue;

I'm trying to use a combination of Consul (via the Docker image progrium/consul), Registrator (also via Docker image progrium/registrator) and Consul -Template to automatically generate an HTML file showing the automatically assigned external port and IP for all Docker containers started that expose a tag 'proxyable' (these tags are registered against the service in Consul via Registrator parsing the environment variables the Docker container has been started with).

My Consul template is (excluding other HTML)...

    {{range services}}
    {{$service:=.}}
    {{range .Tags}}
    {{if eq . "proxyable"}}
    {{range service $service.Name}}<a href="http://{{.Address}}:{{.Port}}">{{$service.Name}}</a>{{end}}
    {{end}}{{end}}{{end}}

Some weird behaviour occurs (using Consul Template 0.6.5). The happy path is;

1. Start Consul Template
2. Start Docker container X with tag 'proxyable'
3. X appears in curl http://consul/v1/catalog/services as expected
4. X appears in templated output as expected.
5. Stop Docker container X.
6. X disappears from curl http://consul/v1/catalog/services as expected
7. X disappears from templated output as expected.
8. Start Docker container X with tag 'proxyable'
9. X appears in curl http://consul/v1/catalog/services as expected
10. X appears in templated output as expected again.
11. Stop Docker container X.
12. X disappears from curl http://consul/v1/catalog/services as expected.
13. X disappears from templated output as expected.

Steps 8 through 13 can be repeated indefinitely, so that's all good...

**HOWEVER** a slight variation (swap steps 1 and 2) seems to introduce unexpected behaviour.

1. Start Docker container X with tag 'proxyable' (was previously step 2).
2. Start Consul Template (was previously step 1).
3. X appears in curl http://consul/v1/catalog/services as expected
4. X appears in templated output as expected.
5. Stop Docker container X.
6. X disappears from curl http://consul/v1/catalog/services as expected
7. X disappears from templated output as expected.
8. Start Docker container X.
9. X appears in curl http://consul/v1/catalog/services as expected
10. **X does NOT appear in templated output... what the?!**
11. Stop Docker container X.
12. X disappears from curl http://consul/v1/catalog/services as expected
13. X still does not appear in templated output... but this is expected now.
14. Start Docker container X
15. X appears in curl http://consul/v1/catalog/services as expected
16. **X now DOES appear in templated output as expected... what the???!!!**

So Consul Template doesn't see the service start up again, when the service was already present when running.

I would maybe have chalked this up as a bug in the Consul container I am using, or Registrator, but that the services are present as desired via the Consul HTTP API suggests this might be a bug in Consul Template?

**Comment by armon** [comment] 2015-02-18 02:55
@jimmcslim @sielaq Could you guys provide the versions of Consul-Template and Consul being used?
Additionally, if you could provide as much logging output as possible during the non-happy path, that would be useful. (gist instead of pasting preferable). Thanks!

**Comment by jimmcslim** [comment] 2015-02-18 04:33
Here's my gist: https://gist.github.com/jimmcslim/b9b9824c35ff70656cbe

Have also commented on the gist with the final log timestamps corresponding with each action.

Am using Consul Template 0.6.5 and Consul 0.4.1 (via Docker image progrium/consul).

**Comment by sielaq** [comment] 2015-02-18 06:35
Sorry for delay - time difference. 

@armon - I have exactly same config like @jimmcslim : I use Consul Template 0.6.5 and Consul 0.4.1 too, also docker images are registered with progrium/consul - and exactly only one consul instance is running - becasue its my sandbox, not a production (I can easili scale it).

What I can do first is giving you my sandbox,
https://github.com/sielaq/paas-in-a-box 
where everything is set up (vagrant), example is there - 
./build-docker-image.sh && ./start_with_marathon.sh
and scaling up/down can be done via marathon gui port 8080

In meantime I will try to reproduce it and create more logs.

**Comment by sielaq** [comment] 2015-02-18 07:14
here is my gist: https://gist.github.com/sielaq/91a7036d05afb6eb26f5

**Comment by armon** [comment] 2015-02-18 21:41
@sielaq @jimmcslim Thanks for the additional logging information. I think we now have a handle on what the issue is. The fix is a more complex question however.

What we believe is happening, is that at the core there is an outer loop on "services" and an inner loop on python1 / python2. Under the hood, each of these represents a blocking query to Consul (basically an edge-triggered long poll). The subtle bit, is that there is a data dependence between the different watches. The "services" view is a collection of any service which has an instance (healthy or not), while the specific "python1" view contains only the instances of that service.

If all instances of python1 are deregistered, we expect 2 simultaneous updates:
1) The "services" view no longer reflects python1
2) The "python1" view returns the empty list.

Where a problem arrises is that these updates happen independently, and can race to be in arbitrary order. This means consul-template will always receive one update before the other (at a minimum it will process them sequentially and apply an arbitrary ordering). Now, depending on the order of those updates the result is either expected or unexpected. This does not affect the `-once` case, since it has no previous state, and must regardless wait for the latest data.

In the case that "services" returns first, we properly stop tracking "python1" and avoid emitting any stanza's for it. In the case "python1" returns first, we will generate the stanza BUT with an empty host list (as you've reported).

This is the heart of the issue as far as we know. What can be done about it is a few options:
1) consul-template could understand the data dependence semantics between all these dependencies and attempt to work around them. This introduces a huge amount of complexity and is not practical.

2) Introduce a "sleep" period to guard against the racy updates to allow both updates before rendering. This is probably the most sane, since most likely a `-wait 200msec` is enough to catch this problem.

3) The template can guard against this more actively. If you anticipate the potential "race", then you can instead do something like:

```
{{range services}}{{$service:=.Name}}{{range .Tags}}{{if or (eq . "webapp") (eq . "haproxy")}}
   {{$backends := service $service "passing" }}
   {{ if $backends.Length > 0 }}
    acl acl_{{$service}} hdr(host) -i {{$service}}.service.consul
    use_backend backend_{{$service}} if acl_{{$service}}
   {{ end }}
{{end}}{{end}}{{end}}
{{range services}}{{$service:=.Name}}{{range .Tags}}{{if or (eq . "webapp") (eq . "haproxy")}}
   {{$backends := service $service "passing" }}
   {{ if $backends.Length > 0 }}
    backend backend_{{$service}}
      balance leastconn
      option http-server-close
  {{range $backends }}    server {{.Name}} {{.Address}}:{{.Port}} maxconn 64
  {{ end }}
  {{end}}
{{end}}{{end}}{{end}}
```

The key here is the more aggressive guards based on the length of the backend results. This will handle the race between the two watchers as well, but places some additional burden to think about this.

Since you guys have a working setup to repro this, could you please try solution 2 first, with a 100-200msec wait period and see if you can reproduce the issue? If it seems to solve it, then we can make that a reasonable default to fix this in the 95% case, and document the work arounds for the other cases.

Thanks!

**Comment by jimmcslim** [comment] 2015-02-19 00:40
I can confirm that adding -wait 0.2s (-wait 200msec didn't work, 'unknown unit msec in duration 200msec') to the consul-template command line arguments resulted in expected behaviour (i.e. at step 10 in the variation container X DOES appear in the templated output as desired).

**Comment by sielaq** [comment] 2015-02-19 14:24
After adding "-wait 0.2s" (I started from that point since this helped to @jimmcslim) but unfortunately I was able to reproduce the error again. Then I wanted to go with you 3rd approach. I had modified it little bit: 
```
{{ if gt $backends.Length 0 }}
...
{{{ end }}}
```
but I got error:
```
 can't evaluate field Length in type []*dependency.HealthService
````

@armon, I would agree with you what you say, if this had happenned during the time when nothing was changed (no more backends added/removed after race condition is encountered). But the inconsistancy stays like that, even if I add more backends of the same service later on.

Which means that it is not a race condition, it looks more like a "block mode" I can add more and more backends and nothing gonna change - until I remove all backend of service and start adding them again.

**Comment by sethvargo** [comment] 2015-02-19 17:00
@sielaq Armon was providing some psuedo-code to get you started. I believe you want `{{if gt len($backends) 0}}` or something like that. Go's text/template documentation should have some examples.

**Comment by sethvargo** [comment] 2015-02-19 22:05
Hi @sielaq @jimmcslim,

We just release Consul 0.5 and Consul Template 0.7.0. While there is no indication this will be fixed by either of those releases, it would be very helpful if you could try these new releases and see if you are still experiencing the issue.

**Comment by sielaq** [comment] 2015-02-20 11:30
Hi @sethvargo and @armon 

I have used  Consul 0.5 and Consul Template 0.7.0, but unfortunately still the same
I have created a dummy script to reproduce it, so please don't laugh :) 

https://gist.github.com/sielaq/734a2b130c9cd03cd2d1

REQUIREMENTS:
Consul have to be running, 
and you should have consul-template in working directory
```
export CONSUL_IP=<YOU_IP>
./reproduceit.sh
```
consul-template logs you should find in ```/tmp/consul_template.debug```

I hope this gonna help

**Comment by sethvargo** [comment] 2015-02-20 14:55
Hey @sielaq 

Dummy script or not, that is **incredibly** helpful! Thank you so much for putting that together! :smile: /cc @armon

**Comment by jimmcslim** [comment] 2015-02-21 08:08
Looks good to me, contingent on not starting/stopping services in the 5 seconds period.

**Comment by sielaq** [comment] 2015-02-28 16:52
Hi @sethvargo,
were you able to reproduce the issue, or am I the only one here who experiencing something wired :smile: ?  If you need some more details, please tell me.

**Comment by sethvargo** [comment] 2015-02-28 17:30
Hi @sielaq 

I have not had time to dig into this.

**Comment by sielaq** [comment] 2015-02-28 17:41
ok, understand ;)

**Comment by jefferai** [comment] 2015-03-20 15:46
I have been hitting this behavior as well; the example at https://github.com/hashicorp/consul-template#querying-all-services is a perfect reproducible test case(!).

I can also confirm that @sielaq 's workaround (using two instances of consul-template, one to generate the other's template in order to explicitly serialize the calls) works for me as well.

**Closed** 2015-03-30 22:02 UTC

**Comment by sielaq** [comment] 2015-03-31 07:40
Thanks a lot @sethvargo, I own you few :beers: !
