### ISSUE TITLE
Add sprig function support

### ISSUE THREAD

**Issue by bitsofinfo** [hashicorp/consul-template#1206] opened 2019-04-19 16:03 UTC
Please consider adding sprig go templating function support, its used in helm etc and would be a great additional of capabilities into consul-template

https://github.com/Masterminds/sprig

**Comment by bitsofinfo** [comment] 2019-10-30 18:27
please, pretty please

**Comment by boarder981** [comment] 2019-10-30 19:13
This would be amazing.  Sprig has saved me a lot of trouble with helm charts, and would be great to have in consul-template as well!

**Comment by CasparChou** [comment] 2019-11-08 06:30
need this

**Comment by bitsofinfo** [comment] 2019-11-12 16:32
https://github.com/hashicorp/consul-template/blob/34cd324a344a03571d8dbeb73135ecc2ab9345eb/template/template.go#L223

might be collisions, might have to use a prefix name in the mappings:  http://masterminds.github.io/sprig/

**Comment by Chinikins** [comment] 2022-01-14 19:05
I think several of us would appreciate this PR picked up: https://github.com/hashicorp/consul-template/pull/1312

**Comment by eikenb** [comment] 2022-03-11 19:58
https://github.com/hashicorp/consul-template/pull/1312 was merged!

**Closed by eikenb** 2022-03-11 19:58 UTC
Labels: enhancement

**Comment by jakubgs** [comment] 2022-03-23 10:44
That's very cool, but are there any plans to upgrade to newer version, like `3.2.1`?

The newer versions add support for a lot of useful operations for dicts, like for example [`get`](https://masterminds.github.io/sprig/dicts.html#get) in [3.0.0](https://github.com/Masterminds/sprig/releases/tag/v3.0.0) and [`dig`](https://masterminds.github.io/sprig/dicts.html#dig) in [3.2.0](https://github.com/Masterminds/sprig/releases/tag/v3.2.0).

**Comment by eikenb** [comment] 2022-03-23 19:37
The problem is compatibility. Sprig 3 breaks compatibility with Sprig 2 which is what was merged. We could do a backwards incompatible update, but I don't like to do that if possible. Adding a whole other sprig3* namespace is not really appealing either. I'm going to think about the best solution.

If you'd like to keep this more on the radar, maybe file a separate feature request issues. Maybe others will have an better idea on integrating sprig3 or at least that will be a place to track interest and priority. Thanks.

**Comment by jakubgs** [comment] 2022-03-23 21:42
Thanks for explaining. Didn't know the switch to `3.0.0` was such a big break from `2.0.0`.

I'm starting to think I'm better off trying to use [hcat](https://github.com/hashicorp/hcat) instead to build something more custom.

**Comment by eikenb** [comment] 2022-03-23 21:53
Consul-template will be ported to use hcat as soon as I have the time. That was always the plan. After that I was considering a v2 template library that would allow more modularity, allow for versioning and give template writers more flexibility... but that is mere speculation at this point. Lots to do to get there.

I also maintain hcat and would be happy to help with any usage. Be warned though that there are a couple more API breaking changes in the plans (not huge, but will require updates) before we hit a stable, semantic versioned, 1.0.

**Comment by eikenb** [comment] 2022-03-23 21:57
> Thanks for explaining. Didn't know the switch to 3.0.0 was such a big break from 2.0.0.

I don't think it is **that** big of a change, but they do list a few backwards incompatibilities (they list 1 breaking change for `^` as necessitating the major version bump) and I have no way to tell if those will hit users or not. So even for small compatibility issues, breaking something working is still possible and is what I'd like to avoid.

**Comment by jakubgs** [comment] 2022-03-23 21:59
Yeah, that's what I thought it was for, and I'm aware it's unstable, that's fine by me.

My use case is that I have Consul service which represent backends/upstreams for an Nginx Reverse proxy, for which the config is generated using `consul-template`. This works fine if the relation of service <-> domain is 1 to 1. If it's N to 1 - meaning multiple upstream servers per domain - the templating I have simply uses the last service for the given domain in the query result. What I'd like to do is to first bunch up services together based on domain, and then render separate configs for each proxy so it can have multiple upstreams.

I was hoping to use dicts and `get`/`dig`/`set` and list operations to do that, but that might be just more complex than it needs to be. It might be simpler just to write this logic directly in Go or Python and have much more flexibility for extending it in the future. I think I would definitely be interesting in learning how to use `hcat`.

**Comment by eikenb** [comment] 2022-03-23 22:05
There might be a way to do that with CT, I've seen some pretty crazy setups. You could ask on the discuss forum where others who are much better at the templates than I am (shout-out to @blake ) could see it and have a chance to respond. Just a thought.

**Comment by eikenb** [comment] 2022-03-23 22:06
Discuss forum I mentioned... https://discuss.hashicorp.com/tags/c/consul/29/consul-template

**Comment by jakubgs** [comment] 2022-03-23 22:07
Will do, thanks.

**Comment by blake** [comment] 2022-03-23 22:11
@jakubgs, I shared a template earlier today sounds like it does some of what you're looking for. Take a look  and let me know if this meets your needs. https://discuss.hashicorp.com/t/consul-template-nginx-vhost/4425/2?u=blake

**Comment by jakubgs** [comment] 2022-03-23 22:19
Thanks @blake, interesting. I will have to read into it and do some tests, it does appear to use some elements of dark magic.

**Comment by jakubgs** [comment] 2022-03-25 13:00
With very minimal modifications I managed to get your example working for my own setup!.

Thanks a bunch @blake, really cool stuff. And now I can ever filter by just tags, which is what I wanted from the start.
