### ISSUE TITLE
nested vault information

### ISSUE THREAD

**Issue by wstaples** [hashicorp/consul-template#564] opened 2016-03-03 15:28 UTC
I have a consul-template setup with:
```
{{range ls "app/"}}
{{.Key}}={{.Value}}{{ end }}
```

Which works fine to iterate through all of the sub keys under app. My question is how can I introduce a vault information in this way?

could I do multiple passes? for example I could set a consul key app/database_password with the value of

`{{with vault "secret/passwords"}}{{.Data.password}}{{end}}`

and somehow have it resolve that 'with vault' statement?

what I would really like to do is build a template based on the keys in consul so I don't have to keep updating my .ctmpl file every time someone wants to add a new key.

**Comment by sethvargo** [comment] 2016-03-03 15:39
Hi @wstaples 

Unfortunately this is not possible. This is not a limit of Consul Template, but a limit of Go's templating language. Dupe of https://github.com/hashicorp/consul-template/issues/544. Thanks! :smile:

**Closed by sethvargo** 2016-03-03 15:39 UTC
