### ISSUE TITLE
Weird newlines in toYAML

### ISSUE THREAD

**Issue by miked63017** [hashicorp/consul-template#919] opened 2017-03-28 18:32 UTC
### Consul Template version
0.18.1

### Configuration

```liquid
{{ tree "somefolderinconsul" | explode | toYAML }}
```

### Command

```shell
consul-template -template "test.template:output.test" -once -consul-addr some.consul.address:8500
```

### Example Consul Data

somefolderinconsul/testKey = "{{ key "some/other/key/in/consul" }}.{{ key "another/one" }}.{{ key "and/one/final" }}"

### Expected behavior

I would have expected yaml to be output as follows:
```yaml
testKey: '{{ key "some/other/key/in/consul" }}.{{ key "another/one" }}.{{ key "and/one/final"}}'
```

### Actual behavior

Note the newline after the final key
```yaml
testKey: '{{ key "some/other/key/in/consul" }}.{{ key "another/one" }}.{{ key "and/one/final"
  }}'
```

### Steps to reproduce

1. Create consul data
2. create template
3. run command

### Notes
I planned on running the template through consul-template twice, not for double interpolation to happen, but the newline breaks the second run. I have reproduced this several times locally with the newlines happening only when using {{key "somekey"}} blocks. However they are ins different places, and sometimes you can use one key block, sometimes two, but three key blocks always throws a newline in there.

This very well could be a consul issue, but I don't see anything standing out in the logs there, or even here when I run with trace log-level.

I should also mention, if you only explode the data, a newline is not added, the newline is only added when you go toYAML.

**Comment by sethvargo** [comment] 2017-03-28 19:30
Hi @miked63017 

Can you please query the API directly and look at the response? Are you sure the newline isn't in the key itself in consul's KV store?

**Comment by miked63017** [comment] 2017-03-29 18:22
I checked, seems its not, I have also tried with various values and get the same results.

```
lstl8e22g8wm-m:GitRepos s0043826$ curl -s http://my.consul.instance:8500/v1/kv/somefolderinconsul/testKey | jq -r .[0].Value | base64 -D
{{ key "some/other/key/in/consul" }}.{{ key "another/one" }}.{{ key "and/one/final" }}
```

**Comment by sethvargo** [comment] 2017-03-29 20:53
Hi @miked63017 

Thank you for the reply. I'm a bit confused - is the value of your key a template itself? I'm not sure if I'm following the issue. What is the data that you're feeding into `toYAML` exactly?

**Comment by miked63017** [comment] 2017-03-29 22:09
Yes @sethvargo, it is the contents of the final template, which will be parsed in a secondary run.

Basically I am trying to make my templates completely dynamic since they are all outputting yaml. Most things do not have secondary key/value interpolation needed, but a few do. I am not expecting double interpolation to happen, just to get the contents of the value in consul which happens to be template syntax.

**Comment by sethvargo** [comment] 2017-03-29 22:17
Hi @miked63017 

Sorry. I'm not really sure the best way to assist. We use a third-party library for parsing/generating YAML, and without the exact setup on my end to replicate, I don't know how much more I can help debug 😦 . I have a suspicion this is something with your local setup, since many people use the yaml functionality without issue. I just don't have a good way to help track it down for you.

**Comment by miked63017** [comment] 2017-03-29 23:19
I described steps to reproduce above, all you need is a consul server which I am assuming you have. I will script a setup to reproduce if needed, will have some time tomorrow to do it.

**Comment by sethvargo** [comment] 2017-03-29 23:55
Hi @miked63017 

Sorry I wasn't clear. I _can_ reproduce this, but I don't know if I have the same setup as you locally. What I'm saying is that [we don't do anything special and use a third-party library for generating the YAML](https://github.com/hashicorp/consul-template/blob/e79894aad0b3789b93d0372e23f6eb0d2b75b35a/template/funcs.go#L899-L906). This looks to be an upstream issue, and I have no idea why.

**Comment by sethvargo** [comment] 2017-03-30 00:00
This is reproducible on "long strings" in general:

```
➜  ~  consul kv get foo/bar
abcd1234 abcd1234 abcd1234 abcd1234 abcd1234 abcd1234 abcd1234 abcd1234 abcd1234 abcd1234 abcd1234 abcd1234 abcd1234
➜  ~  consul-template -template=in.tpl -dry -once
>
bar: abcd1234 abcd1234 abcd1234 abcd1234 abcd1234 abcd1234 abcd1234 abcd1234 abcd1234
  abcd1234 abcd1234 abcd1234 abcd1234
```

It looks like the library (or maybe the YAML spec) doesn't permit long lines, so it's trying to be "helpful" and wrap them. Nonetheless, this still appears to be an upstream issue.

**Comment by ryanuber** [comment] 2017-03-30 18:09
I agree this is an upstream issue, though I would also say that technically it seems like an incompatibility with YAML's line breaking semantics and Go's templating engine. From the YAML 1.2 spec:

> Motivated by HTML’s end-of-line normalization, YAML’s line folding employs an intuitive method of handling line breaks. A single line break is folded into a single space, while empty lines are interpreted as line break characters. This technique allows for paragraphs to be word-wrapped without affecting the canonical form of the scalar content.

So, if the YAML was deserialized, you should get the correct text back as expected, but since it is not deserailized, and it's going right back into Go's templating engine, that causes issues.

Note that you can use `toJSON` in place of `toYAML`. From the YAML spec:

> YAML can therefore be viewed as a natural superset of JSON, offering improved human readability and a more complete information model. This is also the case in practice; every JSON file is also a valid YAML file.

The format isn't as pretty, but that might get you past this without waiting for a fix upstream in the YAML library we use.

**Comment by sethvargo** [comment] 2017-05-09 18:31
Hi there,

I'm going to close this, since it appears to be upstream and actually part of the spec. If you have any additional questions, we would be happy to answer them!

**Closed by sethvargo** 2017-05-09 18:31 UTC
