### ISSUE TITLE
docker compile fails on Linux

### ISSUE THREAD

**Issue by tburt11** [hashicorp/consul-template#784] opened 2016-11-10 15:45 UTC
On any Linux version...

Clone this repo and execute "make dev" as described in README results in:

root@dora:~/consul-template# make dev
cut: only one type of list may be specified
Try 'cut --help' for more information.

A bit of debugging reveals that the makefile is executing the "cut" command with multiple fields.  This syntax is not supported on Linux but is compatible with the Mac.

+PROJECT := $(shell echo $(CURRENT_DIR) | rev | cut -d'/' -f1 -f2 -f3 | rev)

**Comment by sethvargo** [comment] 2016-11-10 21:41
Hi there,

Thanks for reporting. This is a dupe of https://github.com/hashicorp/consul-template/pull/781, which will be merged before the next release. For now, you can manually apply that patch or just edit the Makefile. Thanks and sorry!

**Closed by sethvargo** 2016-11-10 21:41 UTC
