### ISSUE TITLE
migrate templating engine to Hugo

### ISSUE THREAD

**Issue by skippy** [hashicorp/consul-template#503] opened 2016-01-05 06:20 UTC
They offer some nice extensions, esp for this issue: https://github.com/golang/go/issues/10608

it is difficult to handle common cases like `if no services are running, do this`.  Nested variables can solve that, along with a few other common cases (e.g. a running counter of up or down services).

I don't know if I'm asking for the moon here or not, but there it is :)

**Comment by sethvargo** [comment] 2016-01-05 16:30
Dupe of https://github.com/hashicorp/consul-template/issues/447, please watch that issue. Thanks!

**Closed by sethvargo** 2016-01-05 16:30 UTC

**Comment by skippy** [comment] 2016-01-05 18:23
good call!  Thank you sir!
