### ISSUE TITLE
Ability to set user:group for template

### ISSUE THREAD

**Issue by spinx** [hashicorp/consul-template#497] opened 2015-12-28 16:55 UTC
There's Perms option to change template permissions, why wouldn't there be 'chown' capability as well ?

There's lots of use cases where you would want the destination file to be owned by someone other than the user running consul-template.

You could run multiple instances for each user, sure, but that's kinda lame. 

Looking at the code this should be fairly simple. Should I give it a go ?

**Comment by sethvargo** [comment] 2015-12-28 20:46
Unfortunately it's not that easy.

Duplicate of https://github.com/hashicorp/consul-template/issues/494 and https://github.com/hashicorp/consul-template/issues/461. Please see the comments on those tickets for more information.

**Closed by sethvargo** 2015-12-28 20:46 UTC
