### ISSUE TITLE
range service is not working

### ISSUE THREAD

**Issue by bitsofinfo** [hashicorp/consul-template#757] opened 2016-10-19 23:28 UTC
Using latest version

My Template: **(results in no output)**
```
{{range service "my-service-1.0"}}
      BalancerMember http://{{.Address}}:{{.Port}} loadfactor=1{{end}}
```

consul-template log
```
2016/10/19 23:17:05.439670 [DEBUG] ("service(my-service-1.0)") Consul returned 0 services
```

If I manually curl to: `http://consul:8500/v1/health/service/my-service-1.0` I get back legit info:

```
[
  {
    "Node":{
      "Node":"e10e1e0192d9",
      "Address":"127.0.0.1",
      "TaggedAddresses":{
        "lan":"127.0.0.1",
        "wan":"127.0.0.1"
      },
      "CreateIndex":4,
      "ModifyIndex":69757
    },
    "Service":{
      "ID":"xxx:small_liskov:4000",
      "Service":"my-service-1.0",
      "Tags":null,
      "Address":"192.168.1.2",
      "Port":40002,
      "EnableTagOverride":false,
      "CreateIndex":69624,
      "ModifyIndex":69624
    },
    "Checks":[
      {
        "Node":"e10e1e0192d9",
        "CheckID":"serfHealth",
        "Name":"Serf Health Status",
        "Status":"passing",
        "Notes":"",
        "Output":"Agent alive and reachable",
        "ServiceID":"",
        "ServiceName":"",
        "CreateIndex":4,
        "ModifyIndex":4
      }
    ]
  }
]
```

What am I missing here?

**Comment by sethvargo** [comment] 2016-10-20 00:17
Hi there,

This is a duplicate of https://github.com/hashicorp/consul-template/issues/295. It is _strongly_ discouraged by both Consul and Consul Template to use dots (periods) in service names. Dots are used as the DNS tags. In your example, Consul Template is looking for a service named "0" with a tag of "my-service-1".

**Closed by sethvargo** 2016-10-20 00:17 UTC
