### ISSUE TITLE
Improve error reporting

### ISSUE THREAD

**Issue by c4milo** [hashicorp/consul-template#275] opened 2015-05-08 16:56 UTC
I have an error in one of my templates it seems, but I can't really tell what's going on based on these reported errors: 

```
Consul Template returned errors:
runner: config: walk error: 1 error(s) occurred:

* Line 5, column 11: syntax errorConsul Template returned errors:
runner: config: walk error: 1 error(s) occurred:

* Line 5, column 11: syntax errorConsul Template returned errors:
runner: config: walk error: 1 error(s) occurred:

* Line 5, column 11: syntax errorConsul Template returned errors:
runner: config: walk error: 1 error(s) occurred:

* Line 5, column 11: syntax errorConsul Template returned errors:
runner: config: walk error: 1 error(s) occurred:

* Line 5, column 11: syntax errorConsul Template returned errors:
runner: config: walk error: 1 error(s) occurred:

* Line 5, column 11: syntax errorConsul Template returned errors:
runner: config: walk error: 1 error(s) occurred:

* Line 5, column 11: syntax errorConsul Template returned errors:
runner: config: walk error: 1 error(s) occurred:

* Line 5, column 11: syntax errorConsul Template returned errors:
runner: config: walk error: 1 error(s) occurred:

* Line 5, column 11: syntax errorConsul Template returned errors:
runner: config: walk error: 1 error(s) occurred:
```

This is my template: 

```
auto_accept: {{key "q/stg/salt/master/auto_accept"}}

file_roots:
  base:
    - {{key "q/stg/salt/master/file_roots/base"}}

fileserver_backend:
  - {{key "q/stg/salt/master/backend"}}

gitfs_remotes:
  - {{key "q/stg/salt/master/backends/git/remote"}}

gitfs_user: {{key "q/stg/salt/master/backends/git/user"}}
gitfs_password: {{key "q/stg/salt/master/backends/git/password"}}
gitfs_root: {{key "q/stg/salt/master/backends/git/root"}}
gitfs_base: {{key "q/stg/salt/master/backends/git/base"}}
gitfs_provider: {{key "q/stg/salt/master/backends/git/provider"}}

```

**Comment by ryanuber** [comment] 2015-05-08 17:00
Hey @c4milo, do you use configuration files to start consul-template? It looks like the error may be in one of the configuration files provided. I agree though, the error could be more helpful. Marking as an enhancement!

**Comment by c4milo** [comment] 2015-05-08 17:04
@ryanuber yes, but it looks like the issue is with the template as I've removed lines and made changes and the line reported in the log changes. Here are my configurations just in case I'm being misled by consul-template: 

```
retry = "5s"

ssl {
	enabled = true
	verify = true
	cert = "/etc/consul.d/ssl/consul.cert"
	ca_cert = "/etc/consul.d/ssl/ca.cert"
}

template {
	source = "/etc/consul.d/template/templates/salt-master.ctmpl"
	destination = "/etc/salt/master"
	command = "stop salt-master; start salt-master"
}
```

**Comment by c4milo** [comment] 2015-05-08 17:06
Ah here is my Consul configuration: 

```
{
        "data_dir": "/mnt/consul",
        "encrypt": "Hashicorp rocks",
        "log_level": "INFO",
        "enable_syslog": true,
        "ca_file": "/etc/consul.d/ssl/ca.cert",
        "cert_file": "/etc/consul.d/ssl/consul.cert",
        "key_file": "/etc/consul.d/ssl/consul.key",
        "verify_incoming": true,
        "verify_outgoing": true,
        "ports": {
                "dns": 53
        },
        "recursors": ["8.8.8.8", "8.8.4.4"]
}
```

**Comment by ryanuber** [comment] 2015-05-08 17:13
Hmm, I'm not sure where exactly the problem is at first glance. I'll try to repro this locally and see if I get the same error.

**Comment by c4milo** [comment] 2015-05-08 17:15
maybe I need to do something else to really enable SSL in Consul? that just came to my mind for some reason.

**Comment by c4milo** [comment] 2015-05-08 18:11
Here is more context: 
![](https://cldup.com/oAy_sOcH_S.png)

**Comment by c4milo** [comment] 2015-05-08 18:17
@ryanuber I think consul-template is getting lost when I set `-config` to a directory

**Comment by sethvargo** [comment] 2015-05-10 04:51
@c4milo sorry you are having problems with CT.

I think the issue here is that you have your CT templates in the same directory as your configuration files. CT will walk and recurse into subdirectories when given the `-config` option, so it's actually ingressing your _templates_ as configs. 

Once https://github.com/hashicorp/consul-template/pull/278 is merged, you'll see the following error which might have made that more obvious:

```text
Consul Template returned errors:
runner: config: walk error: config: error decoding "config/templates/salt-master.ctmpl": Line 1, column 2: syntax error
```

**Comment by c4milo** [comment] 2015-05-10 06:36
Yes sir, I worked around this already, thanks!.

**Closed** 2015-05-13 01:26 UTC
Labels: Enhancement
