### ISSUE TITLE
Service name with . (dot) not found

### ISSUE THREAD

**Issue by hermansc** [hashicorp/consul-template#304] opened 2015-06-04 11:09 UTC
Hi.

Is it possible to disable the pattern matching for name, tag, datacenter and port? I have a service called `foo-bar-1.0-8080` i.e. version 1.0 of the service "foo-bar" running on port 8080. This name, in my case, is generated from gliderlabs/registrator (https://github.com/gliderlabs/registrator).

Trying to use the mentioned service name it doesn't find any services since it (I'm guessing) looks for tag `0-8080` which doesn't exist.

So: can I disable the tag matching or escape the dot?

EDIT: Oh, and I should add that I've temporarily worked around this by specifying `SERVICE_8080_NAME=foo-bar-8080` when starting my container - overriding the way the registrator builds up the service name using the base name of the docker container.

**Comment by sethvargo** [comment] 2015-06-04 14:05
Hi @hermansc 

This is actually a duplicate of https://github.com/hashicorp/consul-template/issues/295 :smile:. We discourage the use of `.` in service names.

**Closed by sethvargo** 2015-06-04 14:05 UTC
