### ISSUE TITLE
Consul 0.7.1.dev byKey sometimes works, sometimes does not

### ISSUE THREAD

**Issue by gmr** [hashicorp/consul-template#226] opened 2015-03-13 17:34 UTC
I am generating a YAML file with nested keys, dynamically creating a key that I am traversing with ``tree | byKey``.  In every iteration of the high level loop (``{{range key $items | parseJSON}}``), it seems to randomly fail to construct the values in the ``baz`` block in the ``{{range $key, $pairs := tree $baz}}`` section.

I have put validation in place that the key for ``$baz`` is valid, temporarily including it in the rendered template.

Every time I run ``HOSTNAME=`hostname -f` consul-template -config=/etc/consul-template.d/ -dry -once `` it will properly fill out the config section across the various ``$items`` entries at random.

Here is the template that is randomly failing:
```
%YAML 1.2
---
Items:{{with $hostname := env "HOSTNAME"}}{{with $items := printf "sample/assignments/%s" ($hostname) }}{{range key $items | parseJSON}}
  {{.}}:
    connections: {{range service "rabbitmq"}}
      - {{.Node}}{{end}}
    foo: {{with $foo := printf "sample/items/%s/foo" (.)}}{{ key $foo }}{{end}}
    {{with $baz := printf "sample/items/%s" (.)}}tree-key: {{$baz}}
      {{range $key, $pairs := tree $baz | byKey}}{{$key}}:{{range $pairs}}
        {{.Key}}: {{.Value}}{{end}}{{end}}{{end}}{{end}}{{end}}{{end}}
```

In the following gist, I've included the template, the data used,  along with three different examples of what I get when I run ``HOSTNAME=`hostname -f` consul-template -config=/etc/consul-template.d/ -dry -once``, the expected output, the data used, and a dump from consul using ``curl http://localhost:8500/v1/kv/sample/?recurse | json_pp``:

https://gist.github.com/gmr/dd66d7cb5722f25a9f3e

Please let me know if I'm doing something wrong or if you need anything else from me to recreate the issue.

**Comment by hoffoo** [comment] 2015-03-13 21:40
this looks like #211

**Comment by sethvargo** [comment] 2015-03-17 03:13
This is a duplicate of #211. Unfortunately I haven't figured it out yet. Please track that issue instead.

**Closed by sethvargo** 2015-03-17 03:13 UTC
